/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ContinuousCore } from "../core.js";
import { appendForm, encodeJSON, normalizeBlob } from "../lib/encodings.js";
import {
  bytesToBlob,
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { ContinuousError } from "../models/errors/continuous-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Build Simulator
 *
 * @remarks
 * Creates a Simulator from an OpenAPI or WSDL source. The build runs asynchronously. Send multipart/form-data with one JSON request part, and one spec file part for a spec build.
 */
export function simulatorsBuildSimulator(
  client: ContinuousCore,
  request: operations.BuildSimulatorRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.Simulator,
    | errors.ErrorT
    | ContinuousError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: ContinuousCore,
  request: operations.BuildSimulatorRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      models.Simulator,
      | errors.ErrorT
      | ContinuousError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(operations.BuildSimulatorRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = new FormData();

  appendForm(
    body,
    "request",
    encodeJSON("request", payload.request, { explode: true }),
  );
  if (payload.spec !== undefined) {
    if (isBlobLike(payload.spec)) {
      const file = payload.spec;
      const blob = await normalizeBlob(file);
      const name = "name" in file ? (file.name as string) : undefined;
      appendForm(body, "spec", blob, name);
    } else if (isReadableStream(payload.spec.content)) {
      const buffer = await readableStreamToArrayBuffer(payload.spec.content);
      const contentType = getContentTypeFromFileName(payload.spec.fileName)
        || "application/octet-stream";
      appendForm(
        body,
        "spec",
        bytesToBlob(buffer, contentType),
        payload.spec.fileName,
      );
    } else {
      const contentType = getContentTypeFromFileName(payload.spec.fileName)
        || "application/octet-stream";
      appendForm(
        body,
        "spec",
        bytesToBlob(payload.spec.content, contentType),
        payload.spec.fileName,
      );
    }
  }

  const path = pathToFunc("/v1/simulators")();

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKeyAuth);
  const securityInput = secConfig == null ? {} : { apiKeyAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "build-simulator",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKeyAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    models.Simulator,
    | errors.ErrorT
    | ContinuousError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(202, models.Simulator$inboundSchema),
    M.jsonErr(
      [400, 401, 403, 404, 408, 409, 413, 415, 422, 429],
      errors.ErrorT$inboundSchema,
      { ctype: "application/problem+json" },
    ),
    M.jsonErr([500, 503], errors.ErrorT$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
