/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { credentialsCreateCredential } from "../funcs/credentials-create-credential.js";
import { credentialsDeleteCredential } from "../funcs/credentials-delete-credential.js";
import { credentialsGetCredential } from "../funcs/credentials-get-credential.js";
import { credentialsListCredentials } from "../funcs/credentials-list-credentials.js";
import { credentialsUpdateCredential } from "../funcs/credentials-update-credential.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Credentials extends ClientSDK {
  /**
   * List credentials
   *
   * @remarks
   * Returns the workspace's credentials, newest first. Credential values are never returned.
   */
  async listCredentials(
    request?: operations.ListCredentialsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListCredentialsResponse> {
    return unwrapAsync(credentialsListCredentials(
      this,
      request,
      options,
    ));
  }

  /**
   * Create credential
   *
   * @remarks
   * Stores a connection to a real system: its base URL, the header that carries the credential, and the header value. Returns the credential without its value.
   */
  async createCredential(
    request: models.CreateCredentialRequest,
    options?: RequestOptions,
  ): Promise<models.Credential> {
    return unwrapAsync(credentialsCreateCredential(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete credential
   *
   * @remarks
   * Deletes a credential and its stored value.
   */
  async deleteCredential(
    request: operations.DeleteCredentialRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(credentialsDeleteCredential(
      this,
      request,
      options,
    ));
  }

  /**
   * Get credential
   *
   * @remarks
   * Returns a credential without its value.
   */
  async getCredential(
    request: operations.GetCredentialRequest,
    options?: RequestOptions,
  ): Promise<models.Credential> {
    return unwrapAsync(credentialsGetCredential(
      this,
      request,
      options,
    ));
  }

  /**
   * Update credential
   *
   * @remarks
   * Renames a credential, changes its base URL or header, or replaces its value. Omitted fields keep their current values.
   */
  async updateCredential(
    request: operations.UpdateCredentialRequest,
    options?: RequestOptions,
  ): Promise<models.Credential> {
    return unwrapAsync(credentialsUpdateCredential(
      this,
      request,
      options,
    ));
  }
}
