/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Simulations } from "./simulations.js";
import { Simulators } from "./simulators.js";
import { Worlds } from "./worlds.js";

export class Continuous extends ClientSDK {
  private _simulations?: Simulations;
  get simulations(): Simulations {
    return (this._simulations ??= new Simulations(this._options));
  }

  private _simulators?: Simulators;
  get simulators(): Simulators {
    return (this._simulators ??= new Simulators(this._options));
  }

  private _worlds?: Worlds;
  get worlds(): Worlds {
    return (this._worlds ??= new Worlds(this._options));
  }
}
