/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { simulatorsBuildSimulator } from "../funcs/simulators-build-simulator.js";
import { simulatorsCancelSimulator } from "../funcs/simulators-cancel-simulator.js";
import { simulatorsCloneSimulator } from "../funcs/simulators-clone-simulator.js";
import { simulatorsDeleteSimulator } from "../funcs/simulators-delete-simulator.js";
import { simulatorsGetSimulator } from "../funcs/simulators-get-simulator.js";
import { simulatorsListSimulators } from "../funcs/simulators-list-simulators.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Simulators extends ClientSDK {
  /**
   * List Simulators
   *
   * @remarks
   * Returns all Simulators that the API key can access. Results can be filtered by status.
   */
  async listSimulators(
    request?: operations.ListSimulatorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSimulatorsResponse> {
    return unwrapAsync(simulatorsListSimulators(
      this,
      request,
      options,
    ));
  }

  /**
   * Build Simulator
   *
   * @remarks
   * Starts an asynchronous Simulator build and returns the Simulator with status pending. Builds start in queue order when workspace capacity is available. Send multipart/form-data with a JSON part named request. To build from a document, add a file part named spec with the OpenAPI or WSDL document. For an incremental build, omit spec and set parent_id and instructions.
   */
  async buildSimulator(
    request: operations.BuildSimulatorRequest,
    options?: RequestOptions,
  ): Promise<operations.BuildSimulatorResponse> {
    return unwrapAsync(simulatorsBuildSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Simulator
   *
   * @remarks
   * Deletes a Simulator that has no dependent Worlds, Simulations, or child Simulators.
   */
  async deleteSimulator(
    request: operations.DeleteSimulatorRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(simulatorsDeleteSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Simulator
   *
   * @remarks
   * Returns a Simulator and its current build status.
   */
  async getSimulator(
    request: operations.GetSimulatorRequest,
    options?: RequestOptions,
  ): Promise<models.Simulator> {
    return unwrapAsync(simulatorsGetSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Simulator Build
   *
   * @remarks
   * Requests cancellation of an active Simulator build. The build can finish before cancellation takes effect. A Simulator that is not building is returned unchanged.
   */
  async cancelSimulator(
    request: operations.CancelSimulatorRequest,
    options?: RequestOptions,
  ): Promise<models.Simulator> {
    return unwrapAsync(simulatorsCancelSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Clone Simulator
   *
   * @remarks
   * Creates a ready copy of a ready Simulator in another workspace. The clone has a new ID and the source's image digest; the source is unchanged. The source is the caller's workspace: an API key's own workspace, or X-Workspace-Id for a session. An API key may clone into any other workspace of its organization.
   */
  async cloneSimulator(
    request: operations.CloneSimulatorRequest,
    options?: RequestOptions,
  ): Promise<models.CloneSimulatorResponse> {
    return unwrapAsync(simulatorsCloneSimulator(
      this,
      request,
      options,
    ));
  }
}
