/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { simulationsCreateSimulation } from "../funcs/simulations-create-simulation.js";
import { simulationsDeleteSimulation } from "../funcs/simulations-delete-simulation.js";
import { simulationsForkSimulation } from "../funcs/simulations-fork-simulation.js";
import { simulationsGetSimulation } from "../funcs/simulations-get-simulation.js";
import { simulationsListSimulationSteps } from "../funcs/simulations-list-simulation-steps.js";
import { simulationsListSimulations } from "../funcs/simulations-list-simulations.js";
import { simulationsMintSimulationToken } from "../funcs/simulations-mint-simulation-token.js";
import { simulationsStartSimulation } from "../funcs/simulations-start-simulation.js";
import { simulationsStopSimulation } from "../funcs/simulations-stop-simulation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Simulations extends ClientSDK {
  /**
   * List Simulations
   *
   * @remarks
   * Returns all Simulations that the API key can access. Results can be filtered by status or Simulator.
   */
  async listSimulations(
    request?: operations.ListSimulationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSimulationsResponse> {
    return unwrapAsync(simulationsListSimulations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Simulation
   *
   * @remarks
   * Creates an isolated runtime from a ready Simulator. The response includes its endpoint and a 1-hour token.
   */
  async createSimulation(
    request: models.CreateSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.CreatedSimulation> {
    return unwrapAsync(simulationsCreateSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Simulation
   *
   * @remarks
   * Deletes a Simulation and its saved runtime state. Delete World-owned Simulations through their World.
   */
  async deleteSimulation(
    request: operations.DeleteSimulationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(simulationsDeleteSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Simulation
   *
   * @remarks
   * Returns a Simulation and its current runtime status. The response does not include data-plane tokens.
   */
  async getSimulation(
    request: operations.GetSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsGetSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Fork Simulation
   *
   * @remarks
   * Creates a Simulation with a 1-hour token. The source Simulation continues to run.
   */
  async forkSimulation(
    request: operations.ForkSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.CreatedSimulation> {
    return unwrapAsync(simulationsForkSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Start Simulation
   *
   * @remarks
   * Starts a stopped Simulation from its saved runtime state. Its endpoint becomes available after the runtime starts.
   */
  async startSimulation(
    request: operations.StartSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsStartSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * List Simulation Steps
   *
   * @remarks
   * Returns recorded steps for a running or paused Simulation. Use any step to create a deterministic fork.
   */
  async listSimulationSteps(
    request: operations.ListSimulationStepsRequest,
    options?: RequestOptions,
  ): Promise<models.ListSimulationStepsResponse> {
    return unwrapAsync(simulationsListSimulationSteps(
      this,
      request,
      options,
    ));
  }

  /**
   * Stop Simulation
   *
   * @remarks
   * Stops a Simulation and saves its runtime state. You can start it later from the saved state.
   */
  async stopSimulation(
    request: operations.StopSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsStopSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Mint Simulation Token
   *
   * @remarks
   * Mints an expiring data-plane token. Send it in X-Continuous-Simulation-Token. Other unexpired tokens remain valid.
   */
  async mintSimulationToken(
    request: operations.MintSimulationTokenRequest,
    options?: RequestOptions,
  ): Promise<models.SimulationToken> {
    return unwrapAsync(simulationsMintSimulationToken(
      this,
      request,
      options,
    ));
  }
}
