/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { simulationsCreateSimulation } from "../funcs/simulations-create-simulation.js";
import { simulationsDeleteSimulation } from "../funcs/simulations-delete-simulation.js";
import { simulationsForkSimulation } from "../funcs/simulations-fork-simulation.js";
import { simulationsGetSimulation } from "../funcs/simulations-get-simulation.js";
import { simulationsListSimulationSteps } from "../funcs/simulations-list-simulation-steps.js";
import { simulationsListSimulations } from "../funcs/simulations-list-simulations.js";
import { simulationsMintSimulationToken } from "../funcs/simulations-mint-simulation-token.js";
import { simulationsStartSimulation } from "../funcs/simulations-start-simulation.js";
import { simulationsStopSimulation } from "../funcs/simulations-stop-simulation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Simulations extends ClientSDK {
  /**
   * List Simulations
   *
   * @remarks
   * Returns all Simulations that the API key can access. Results can be filtered by status or Simulator.
   */
  async listSimulations(
    request?: operations.ListSimulationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSimulationsResponse> {
    return unwrapAsync(simulationsListSimulations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Simulation
   *
   * @remarks
   * Creates a Simulation from a ready Simulator and starts it. The response includes the Simulation endpoint and a token that expires in 1 hour. List and get do not return the token.
   */
  async createSimulation(
    request: models.CreateSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.CreatedSimulation> {
    return unwrapAsync(simulationsCreateSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Simulation
   *
   * @remarks
   * Deletes a Simulation and its saved runtime state. Delete World-owned Simulations through their World.
   */
  async deleteSimulation(
    request: operations.DeleteSimulationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(simulationsDeleteSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Simulation
   *
   * @remarks
   * Returns a Simulation and its current status. The response does not include tokens.
   */
  async getSimulation(
    request: operations.GetSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsGetSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Fork Simulation
   *
   * @remarks
   * Creates a new Simulation from the source Simulation's current state, or from an earlier recorded step when you set at_step. The source must be running or paused; a stopped source returns 409 simulation_stopped. Forking does not change the source. The response includes the new endpoint and a token that expires in 1 hour.
   */
  async forkSimulation(
    request: operations.ForkSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.CreatedSimulation> {
    return unwrapAsync(simulationsForkSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Start Simulation
   *
   * @remarks
   * Starts a stopped Simulation from its saved state. The endpoint serves requests once the response returns. A Simulation that is already running or paused is returned unchanged.
   */
  async startSimulation(
    request: operations.StartSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsStartSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * List Simulation Steps
   *
   * @remarks
   * Lists the Simulation's steps in order. Each request that changed state is one step; a request that only reads registers none. Pass a step number as at_step when you fork to start the child from the state after that step. A stopped Simulation returns 409 simulation_stopped; start it first.
   */
  async listSimulationSteps(
    request: operations.ListSimulationStepsRequest,
    options?: RequestOptions,
  ): Promise<models.ListSimulationStepsResponse> {
    return unwrapAsync(simulationsListSimulationSteps(
      this,
      request,
      options,
    ));
  }

  /**
   * Stop Simulation
   *
   * @remarks
   * Stops a Simulation and saves its state. Requests to its endpoint return 409 simulation_stopped until you start it again. A stopped Simulation is returned unchanged.
   */
  async stopSimulation(
    request: operations.StopSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsStopSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Mint Simulation Token
   *
   * @remarks
   * Creates another token for requests to the Simulation endpoint. Send it in the X-Continuous-Simulation-Token header. Earlier tokens stay valid until they expire.
   */
  async mintSimulationToken(
    request: operations.MintSimulationTokenRequest,
    options?: RequestOptions,
  ): Promise<models.SimulationToken> {
    return unwrapAsync(simulationsMintSimulationToken(
      this,
      request,
      options,
    ));
  }
}
