/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { simulatorsBuildSimulator } from "../funcs/simulators-build-simulator.js";
import { simulatorsCancelSimulatorBuild } from "../funcs/simulators-cancel-simulator-build.js";
import { simulatorsDeleteSimulator } from "../funcs/simulators-delete-simulator.js";
import { simulatorsGetSimulator } from "../funcs/simulators-get-simulator.js";
import { simulatorsListSimulators } from "../funcs/simulators-list-simulators.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Simulators extends ClientSDK {
  /**
   * List Simulators
   *
   * @remarks
   * Returns all Simulators that the API key can access. Results can be filtered by status or name.
   */
  async listSimulators(
    request?: operations.ListSimulatorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSimulatorsResponse> {
    return unwrapAsync(simulatorsListSimulators(
      this,
      request,
      options,
    ));
  }

  /**
   * Build Simulator
   *
   * @remarks
   * Creates a Simulator from an OpenAPI or WSDL source. The build runs asynchronously. Send multipart/form-data with one JSON request part, and one spec file part for a spec build.
   */
  async buildSimulator(
    request: operations.BuildSimulatorRequest,
    options?: RequestOptions,
  ): Promise<models.Simulator> {
    return unwrapAsync(simulatorsBuildSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Simulator
   *
   * @remarks
   * Deletes a Simulator that has no dependent Worlds, Simulations, or child Simulators.
   */
  async deleteSimulator(
    request: operations.DeleteSimulatorRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(simulatorsDeleteSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Simulator
   *
   * @remarks
   * Returns a Simulator and its current build status.
   */
  async getSimulator(
    request: operations.GetSimulatorRequest,
    options?: RequestOptions,
  ): Promise<models.Simulator> {
    return unwrapAsync(simulatorsGetSimulator(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Simulator Build
   *
   * @remarks
   * Requests cancellation of an active Simulator build. The build can finish before cancellation takes effect.
   */
  async cancelSimulatorBuild(
    request: operations.CancelSimulatorBuildRequest,
    options?: RequestOptions,
  ): Promise<models.Simulator> {
    return unwrapAsync(simulatorsCancelSimulatorBuild(
      this,
      request,
      options,
    ));
  }
}
