/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { simulationsAdvanceSimulation } from "../funcs/simulations-advance-simulation.js";
import { simulationsCreateSimulation } from "../funcs/simulations-create-simulation.js";
import { simulationsDeleteSimulation } from "../funcs/simulations-delete-simulation.js";
import { simulationsForkSimulation } from "../funcs/simulations-fork-simulation.js";
import { simulationsGetSimulationAdvance } from "../funcs/simulations-get-simulation-advance.js";
import { simulationsGetSimulationToken } from "../funcs/simulations-get-simulation-token.js";
import { simulationsGetSimulation } from "../funcs/simulations-get-simulation.js";
import { simulationsListSimulationAdvanceEvents } from "../funcs/simulations-list-simulation-advance-events.js";
import { simulationsListSimulationSteps } from "../funcs/simulations-list-simulation-steps.js";
import { simulationsListSimulations } from "../funcs/simulations-list-simulations.js";
import { simulationsMintSimulationToken } from "../funcs/simulations-mint-simulation-token.js";
import { simulationsRegenerateSimulationToken } from "../funcs/simulations-regenerate-simulation-token.js";
import { simulationsStartSimulation } from "../funcs/simulations-start-simulation.js";
import { simulationsStopSimulation } from "../funcs/simulations-stop-simulation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Simulations extends ClientSDK {
  /**
   * List Simulations
   *
   * @remarks
   * Returns all Simulations that the API key can access. Results can be filtered by status, Simulator ID, or pinned Simulator digest.
   */
  async listSimulations(
    request?: operations.ListSimulationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSimulationsResponse> {
    return unwrapAsync(simulationsListSimulations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Simulation
   *
   * @remarks
   * Creates a Simulation from a ready Simulator and starts it. The response includes the endpoint and a token. New persistent Simulations keep the token across stop and restart; legacy Simulations receive an expiring token.
   */
  async createSimulation(
    request: models.CreateSimulationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSimulationResponse> {
    return unwrapAsync(simulationsCreateSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Simulation
   *
   * @remarks
   * Deletes a Simulation and its saved runtime state. Delete World-owned Simulations through their World.
   */
  async deleteSimulation(
    request: operations.DeleteSimulationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(simulationsDeleteSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Simulation
   *
   * @remarks
   * Returns a Simulation, its current status, and the actors a request can act as. The response does not include tokens.
   */
  async getSimulation(
    request: operations.GetSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.SimulationDetail> {
    return unwrapAsync(simulationsGetSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Advance Simulation Time
   *
   * @remarks
   * Schedules an absolute clock advance. Each successful advance commits all due local events in one step. World members advance through their World. Poll the returned operation until it completes.
   */
  async advanceSimulation(
    request: operations.AdvanceSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.ClockAdvance> {
    return unwrapAsync(simulationsAdvanceSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Simulation Clock Advance
   *
   * @remarks
   * Returns durable clock progress, the event count, and the committed step or failure.
   */
  async getSimulationAdvance(
    request: operations.GetSimulationAdvanceRequest,
    options?: RequestOptions,
  ): Promise<models.ClockAdvance> {
    return unwrapAsync(simulationsGetSimulationAdvance(
      this,
      request,
      options,
    ));
  }

  /**
   * List Clock Advance Events
   *
   * @remarks
   * Returns the ordered event trace for a committed advance. The Simulation must be running or paused. Forks retain traces in their inherited state.
   */
  async listSimulationAdvanceEvents(
    request: operations.ListSimulationAdvanceEventsRequest,
    options?: RequestOptions,
  ): Promise<models.ListClockAdvanceEventsResponse> {
    return unwrapAsync(simulationsListSimulationAdvanceEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Fork Simulation
   *
   * @remarks
   * Creates a new Simulation from the source Simulation's current state, or from an earlier recorded step when you set at_step. The source must be running or paused; a stopped source returns 409 simulation_stopped. Forking does not change the source. The response includes the new endpoint and the fork's own token. A persistent token survives stop and restart; a legacy token expires.
   */
  async forkSimulation(
    request: operations.ForkSimulationRequest,
    options?: RequestOptions,
  ): Promise<operations.ForkSimulationResponse> {
    return unwrapAsync(simulationsForkSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Start Simulation
   *
   * @remarks
   * Starts a stopped Simulation from its saved state and returns a usable endpoint token. An already running or paused Simulation returns its current token and status.
   */
  async startSimulation(
    request: operations.StartSimulationRequest,
    options?: RequestOptions,
  ): Promise<operations.StartSimulationResponse> {
    return unwrapAsync(simulationsStartSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * List Simulation Steps
   *
   * @remarks
   * Lists the Simulation's steps in order. Each request that changed state is one step; a request that only reads registers none. Pass a step number as at_step when you fork to start the child from the state after that step. A stopped Simulation returns 409 simulation_stopped; start it first.
   */
  async listSimulationSteps(
    request: operations.ListSimulationStepsRequest,
    options?: RequestOptions,
  ): Promise<models.ListSimulationStepsResponse> {
    return unwrapAsync(simulationsListSimulationSteps(
      this,
      request,
      options,
    ));
  }

  /**
   * Stop Simulation
   *
   * @remarks
   * Stops a Simulation and saves its state. Requests to its endpoint return 409 simulation_stopped until you start it again. A stopped Simulation is returned unchanged.
   */
  async stopSimulation(
    request: operations.StopSimulationRequest,
    options?: RequestOptions,
  ): Promise<models.Simulation> {
    return unwrapAsync(simulationsStopSimulation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Current Simulation Token
   *
   * @remarks
   * Returns the current persistent credential, including while stopped, without rotating it. Legacy Simulations require the deprecated token-mint endpoint or explicit regeneration.
   */
  async getSimulationToken(
    request: operations.GetSimulationTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSimulationTokenResponse> {
    return unwrapAsync(simulationsGetSimulationToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Regenerate Simulation Token
   *
   * @remarks
   * Explicitly replaces the current Simulation credential. The previous token stops authenticating when the transaction commits. Reuse the Idempotency-Key to retry safely.
   */
  async regenerateSimulationToken(
    request: operations.RegenerateSimulationTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.RegenerateSimulationTokenResponse> {
    return unwrapAsync(simulationsRegenerateSimulationToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Mint Simulation Token
   *
   * @remarks
   * For an active legacy Simulation, creates another expiring token. For a persistent Simulation, returns its current token without rotating it, including while stopped. Send the token in the X-Continuous-Simulation-Token header.
   */
  async mintSimulationToken(
    request: operations.MintSimulationTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.MintSimulationTokenResponse> {
    return unwrapAsync(simulationsMintSimulationToken(
      this,
      request,
      options,
    ));
  }
}
