/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { worldsBuildWorld } from "../funcs/worlds-build-world.js";
import { worldsCancelWorldBuild } from "../funcs/worlds-cancel-world-build.js";
import { worldsDeleteWorld } from "../funcs/worlds-delete-world.js";
import { worldsGetWorld } from "../funcs/worlds-get-world.js";
import { worldsListWorlds } from "../funcs/worlds-list-worlds.js";
import { worldsStartWorld } from "../funcs/worlds-start-world.js";
import { worldsStopWorld } from "../funcs/worlds-stop-world.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Worlds extends ClientSDK {
  /**
   * List Worlds
   *
   * @remarks
   * Returns all Worlds that the API key can access.
   */
  async listWorlds(
    request?: operations.ListWorldsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListWorldsResponse> {
    return unwrapAsync(worldsListWorlds(
      this,
      request,
      options,
    ));
  }

  /**
   * Build World
   *
   * @remarks
   * Starts an asynchronous World build from one or more ready Simulators and returns the World in the building state. Start the World once it is ready to create its Simulations.
   */
  async buildWorld(
    request: models.BuildWorldRequest,
    options?: RequestOptions,
  ): Promise<models.World> {
    return unwrapAsync(worldsBuildWorld(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete World
   *
   * @remarks
   * Deletes a World, all its Simulations, and their saved runtime states.
   */
  async deleteWorld(
    request: operations.DeleteWorldRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(worldsDeleteWorld(
      this,
      request,
      options,
    ));
  }

  /**
   * Get World
   *
   * @remarks
   * Returns a World, its build instructions, and its Simulator IDs.
   */
  async getWorld(
    request: operations.GetWorldRequest,
    options?: RequestOptions,
  ): Promise<models.World> {
    return unwrapAsync(worldsGetWorld(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel World Build
   *
   * @remarks
   * Cancels an active World build. Repeated cancellation returns the current World.
   */
  async cancelWorldBuild(
    request: operations.CancelWorldBuildRequest,
    options?: RequestOptions,
  ): Promise<models.World> {
    return unwrapAsync(worldsCancelWorldBuild(
      this,
      request,
      options,
    ));
  }

  /**
   * Start World
   *
   * @remarks
   * Starts every Simulation in the World. The first start creates the Simulations; later starts restore them from saved state. The World must be ready or stopped, and the workspace must have room for all members under its active-Simulation limit. A running World is returned unchanged.
   */
  async startWorld(
    request: operations.StartWorldRequest,
    options?: RequestOptions,
  ): Promise<models.World> {
    return unwrapAsync(worldsStartWorld(
      this,
      request,
      options,
    ));
  }

  /**
   * Stop World
   *
   * @remarks
   * Stops a World and saves each Simulation state. You can start the World later from the saved states.
   */
  async stopWorld(
    request: operations.StopWorldRequest,
    options?: RequestOptions,
  ): Promise<models.World> {
    return unwrapAsync(worldsStopWorld(
      this,
      request,
      options,
    ));
  }
}
