/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @continuous-labs/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx credentialsListCredentials.example.ts
 */

import { Continuous } from "@continuous-labs/sdk";

const continuous = new Continuous({
  apiKeyAuth: process.env["CONTINUOUS_API_KEY_AUTH"] ?? "",
});

async function main() {
  const result = await continuous.credentials.listCredentials({});

  console.log(result);
}

main().catch(console.error);
