/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AdvanceWorldRequest = {
  /**
   * World ID.
   */
  id: string;
  /**
   * Stable key for this request. Reuse with the same target returns the same operation.
   */
  idempotencyKey: string;
  body: models.AdvanceTimeRequest;
};

/** @internal */
export type AdvanceWorldRequest$Outbound = {
  id: string;
  "Idempotency-Key": string;
  body: models.AdvanceTimeRequest$Outbound;
};

/** @internal */
export const AdvanceWorldRequest$outboundSchema: z.ZodMiniType<
  AdvanceWorldRequest$Outbound,
  AdvanceWorldRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.string(),
    body: models.AdvanceTimeRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function advanceWorldRequestToJSON(
  advanceWorldRequest: AdvanceWorldRequest,
): string {
  return JSON.stringify(
    AdvanceWorldRequest$outboundSchema.parse(advanceWorldRequest),
  );
}
