/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AdvanceSimulationRequest = {
  /**
   * Simulation ID.
   */
  id: string;
  /**
   * Stable key for this request. Reuse with the same target returns the same operation.
   */
  idempotencyKey: string;
  body: models.AdvanceTimeRequest;
};

/** @internal */
export type AdvanceSimulationRequest$Outbound = {
  id: string;
  "Idempotency-Key": string;
  body: models.AdvanceTimeRequest$Outbound;
};

/** @internal */
export const AdvanceSimulationRequest$outboundSchema: z.ZodMiniType<
  AdvanceSimulationRequest$Outbound,
  AdvanceSimulationRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.string(),
    body: models.AdvanceTimeRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function advanceSimulationRequestToJSON(
  advanceSimulationRequest: AdvanceSimulationRequest,
): string {
  return JSON.stringify(
    AdvanceSimulationRequest$outboundSchema.parse(advanceSimulationRequest),
  );
}
