/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AdvanceSimulationTimeRequest = {
  /**
   * Simulation or World ID.
   */
  id: string;
  /**
   * Stable key for this request. Reuse with the same target returns the same operation.
   */
  idempotencyKey: string;
  body: models.AdvanceTimeInputBody;
};

/** @internal */
export type AdvanceSimulationTimeRequest$Outbound = {
  id: string;
  "Idempotency-Key": string;
  body: models.AdvanceTimeInputBody$Outbound;
};

/** @internal */
export const AdvanceSimulationTimeRequest$outboundSchema: z.ZodMiniType<
  AdvanceSimulationTimeRequest$Outbound,
  AdvanceSimulationTimeRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.string(),
    body: models.AdvanceTimeInputBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function advanceSimulationTimeRequestToJSON(
  advanceSimulationTimeRequest: AdvanceSimulationTimeRequest,
): string {
  return JSON.stringify(
    AdvanceSimulationTimeRequest$outboundSchema.parse(
      advanceSimulationTimeRequest,
    ),
  );
}
