/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type Spec = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BuildSimulatorRequest = {
  request: models.BuildSimulatorRequest;
  /**
   * OpenAPI or WSDL document, UTF-8 encoded, at most 64 MiB. Required unless the request is an incremental build (parent_id and instructions, no spec).
   */
  spec?: Spec | Blob | undefined;
};

export type BuildSimulatorResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Simulator;
};

/** @internal */
export type Spec$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Spec$outboundSchema: z.ZodMiniType<Spec$Outbound, Spec> = z.object(
  {
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  },
);

export function specToJSON(spec: Spec): string {
  return JSON.stringify(Spec$outboundSchema.parse(spec));
}

/** @internal */
export type BuildSimulatorRequest$Outbound = {
  request: models.BuildSimulatorRequest$Outbound;
  spec?: Spec$Outbound | Blob | undefined;
};

/** @internal */
export const BuildSimulatorRequest$outboundSchema: z.ZodMiniType<
  BuildSimulatorRequest$Outbound,
  BuildSimulatorRequest
> = z.object({
  request: models.BuildSimulatorRequest$outboundSchema,
  spec: z.optional(
    z.union([z.lazy(() => Spec$outboundSchema), blobLikeSchema]),
  ),
});

export function buildSimulatorRequestToJSON(
  buildSimulatorRequest: BuildSimulatorRequest,
): string {
  return JSON.stringify(
    BuildSimulatorRequest$outboundSchema.parse(buildSimulatorRequest),
  );
}

/** @internal */
export const BuildSimulatorResponse$inboundSchema: z.ZodMiniType<
  BuildSimulatorResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Simulator$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function buildSimulatorResponseFromJSON(
  jsonString: string,
): SafeParseResult<BuildSimulatorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuildSimulatorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuildSimulatorResponse' from JSON`,
  );
}
