/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { blobLikeSchema } from "../../types/blobs.js";
import * as models from "../index.js";

export type Spec = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BuildSimulatorRequest = {
  request: models.BuildSimulatorRequest;
  /**
   * OpenAPI or WSDL file. A spec build sends it. At most 67,108,864 UTF-8 bytes.
   */
  spec?: Spec | Blob | undefined;
};

/** @internal */
export type Spec$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Spec$outboundSchema: z.ZodMiniType<Spec$Outbound, Spec> = z.object(
  {
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  },
);

export function specToJSON(spec: Spec): string {
  return JSON.stringify(Spec$outboundSchema.parse(spec));
}

/** @internal */
export type BuildSimulatorRequest$Outbound = {
  request: models.BuildSimulatorRequest$Outbound;
  spec?: Spec$Outbound | Blob | undefined;
};

/** @internal */
export const BuildSimulatorRequest$outboundSchema: z.ZodMiniType<
  BuildSimulatorRequest$Outbound,
  BuildSimulatorRequest
> = z.object({
  request: models.BuildSimulatorRequest$outboundSchema,
  spec: z.optional(
    z.union([z.lazy(() => Spec$outboundSchema), blobLikeSchema]),
  ),
});

export function buildSimulatorRequestToJSON(
  buildSimulatorRequest: BuildSimulatorRequest,
): string {
  return JSON.stringify(
    BuildSimulatorRequest$outboundSchema.parse(buildSimulatorRequest),
  );
}
