/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelWorldRequest = {
  /**
   * World ID.
   */
  id: string;
};

/** @internal */
export type CancelWorldRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelWorldRequest$outboundSchema: z.ZodMiniType<
  CancelWorldRequest$Outbound,
  CancelWorldRequest
> = z.object({
  id: z.string(),
});

export function cancelWorldRequestToJSON(
  cancelWorldRequest: CancelWorldRequest,
): string {
  return JSON.stringify(
    CancelWorldRequest$outboundSchema.parse(cancelWorldRequest),
  );
}
