/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelSimulatorBuildRequest = {
  /**
   * Stable Simulator ID.
   */
  id: string;
};

/** @internal */
export type CancelSimulatorBuildRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelSimulatorBuildRequest$outboundSchema: z.ZodMiniType<
  CancelSimulatorBuildRequest$Outbound,
  CancelSimulatorBuildRequest
> = z.object({
  id: z.string(),
});

export function cancelSimulatorBuildRequestToJSON(
  cancelSimulatorBuildRequest: CancelSimulatorBuildRequest,
): string {
  return JSON.stringify(
    CancelSimulatorBuildRequest$outboundSchema.parse(
      cancelSimulatorBuildRequest,
    ),
  );
}
