/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelSimulatorRequest = {
  /**
   * Simulator ID.
   */
  id: string;
};

/** @internal */
export type CancelSimulatorRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelSimulatorRequest$outboundSchema: z.ZodMiniType<
  CancelSimulatorRequest$Outbound,
  CancelSimulatorRequest
> = z.object({
  id: z.string(),
});

export function cancelSimulatorRequestToJSON(
  cancelSimulatorRequest: CancelSimulatorRequest,
): string {
  return JSON.stringify(
    CancelSimulatorRequest$outboundSchema.parse(cancelSimulatorRequest),
  );
}
