/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelWorldBuildRequest = {
  /**
   * Stable World ID.
   */
  id: string;
};

/** @internal */
export type CancelWorldBuildRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelWorldBuildRequest$outboundSchema: z.ZodMiniType<
  CancelWorldBuildRequest$Outbound,
  CancelWorldBuildRequest
> = z.object({
  id: z.string(),
});

export function cancelWorldBuildRequestToJSON(
  cancelWorldBuildRequest: CancelWorldBuildRequest,
): string {
  return JSON.stringify(
    CancelWorldBuildRequest$outboundSchema.parse(cancelWorldBuildRequest),
  );
}
