/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CloneSimulatorRequest = {
  /**
   * Source Simulator ID.
   */
  id: string;
  body: models.CloneSimulatorRequest;
};

/** @internal */
export type CloneSimulatorRequest$Outbound = {
  id: string;
  body: models.CloneSimulatorRequest$Outbound;
};

/** @internal */
export const CloneSimulatorRequest$outboundSchema: z.ZodMiniType<
  CloneSimulatorRequest$Outbound,
  CloneSimulatorRequest
> = z.object({
  id: z.string(),
  body: models.CloneSimulatorRequest$outboundSchema,
});

export function cloneSimulatorRequestToJSON(
  cloneSimulatorRequest: CloneSimulatorRequest,
): string {
  return JSON.stringify(
    CloneSimulatorRequest$outboundSchema.parse(cloneSimulatorRequest),
  );
}
