/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSimulatorRequest = {
  /**
   * Stable Simulator ID.
   */
  id: string;
};

/** @internal */
export type DeleteSimulatorRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSimulatorRequest$outboundSchema: z.ZodMiniType<
  DeleteSimulatorRequest$Outbound,
  DeleteSimulatorRequest
> = z.object({
  id: z.string(),
});

export function deleteSimulatorRequestToJSON(
  deleteSimulatorRequest: DeleteSimulatorRequest,
): string {
  return JSON.stringify(
    DeleteSimulatorRequest$outboundSchema.parse(deleteSimulatorRequest),
  );
}
