/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteWorldRequest = {
  /**
   * Stable World ID.
   */
  id: string;
};

/** @internal */
export type DeleteWorldRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteWorldRequest$outboundSchema: z.ZodMiniType<
  DeleteWorldRequest$Outbound,
  DeleteWorldRequest
> = z.object({
  id: z.string(),
});

export function deleteWorldRequestToJSON(
  deleteWorldRequest: DeleteWorldRequest,
): string {
  return JSON.stringify(
    DeleteWorldRequest$outboundSchema.parse(deleteWorldRequest),
  );
}
