/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSimulationRequest = {
  /**
   * Simulation ID.
   */
  id: string;
};

/** @internal */
export type DeleteSimulationRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSimulationRequest$outboundSchema: z.ZodMiniType<
  DeleteSimulationRequest$Outbound,
  DeleteSimulationRequest
> = z.object({
  id: z.string(),
});

export function deleteSimulationRequestToJSON(
  deleteSimulationRequest: DeleteSimulationRequest,
): string {
  return JSON.stringify(
    DeleteSimulationRequest$outboundSchema.parse(deleteSimulationRequest),
  );
}
