/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteCredentialRequest = {
  /**
   * Credential ID.
   */
  id: string;
};

/** @internal */
export type DeleteCredentialRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCredentialRequest$outboundSchema: z.ZodMiniType<
  DeleteCredentialRequest$Outbound,
  DeleteCredentialRequest
> = z.object({
  id: z.string(),
});

export function deleteCredentialRequestToJSON(
  deleteCredentialRequest: DeleteCredentialRequest,
): string {
  return JSON.stringify(
    DeleteCredentialRequest$outboundSchema.parse(deleteCredentialRequest),
  );
}
