/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ForkSimulationRequest = {
  /**
   * Source Simulation ID.
   */
  id: string;
  body: models.ForkSimulationRequest;
};

export type ForkSimulationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatedSimulation;
};

/** @internal */
export type ForkSimulationRequest$Outbound = {
  id: string;
  body: models.ForkSimulationRequest$Outbound;
};

/** @internal */
export const ForkSimulationRequest$outboundSchema: z.ZodMiniType<
  ForkSimulationRequest$Outbound,
  ForkSimulationRequest
> = z.object({
  id: z.string(),
  body: models.ForkSimulationRequest$outboundSchema,
});

export function forkSimulationRequestToJSON(
  forkSimulationRequest: ForkSimulationRequest,
): string {
  return JSON.stringify(
    ForkSimulationRequest$outboundSchema.parse(forkSimulationRequest),
  );
}

/** @internal */
export const ForkSimulationResponse$inboundSchema: z.ZodMiniType<
  ForkSimulationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CreatedSimulation$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function forkSimulationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ForkSimulationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForkSimulationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForkSimulationResponse' from JSON`,
  );
}
