/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ForkSimulationRequest = {
  /**
   * Stable source Simulation ID.
   */
  id: string;
  body: models.ForkSimulationRequest;
};

/** @internal */
export type ForkSimulationRequest$Outbound = {
  id: string;
  body: models.ForkSimulationRequest$Outbound;
};

/** @internal */
export const ForkSimulationRequest$outboundSchema: z.ZodMiniType<
  ForkSimulationRequest$Outbound,
  ForkSimulationRequest
> = z.object({
  id: z.string(),
  body: models.ForkSimulationRequest$outboundSchema,
});

export function forkSimulationRequestToJSON(
  forkSimulationRequest: ForkSimulationRequest,
): string {
  return JSON.stringify(
    ForkSimulationRequest$outboundSchema.parse(forkSimulationRequest),
  );
}
