/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSimulatorRequest = {
  /**
   * Stable Simulator ID.
   */
  id: string;
};

/** @internal */
export type GetSimulatorRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSimulatorRequest$outboundSchema: z.ZodMiniType<
  GetSimulatorRequest$Outbound,
  GetSimulatorRequest
> = z.object({
  id: z.string(),
});

export function getSimulatorRequestToJSON(
  getSimulatorRequest: GetSimulatorRequest,
): string {
  return JSON.stringify(
    GetSimulatorRequest$outboundSchema.parse(getSimulatorRequest),
  );
}
