/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetSimulationTokenRequest = {
  /**
   * Simulation ID.
   */
  id: string;
};

export type GetSimulationTokenResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CurrentSimulationToken;
};

/** @internal */
export type GetSimulationTokenRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSimulationTokenRequest$outboundSchema: z.ZodMiniType<
  GetSimulationTokenRequest$Outbound,
  GetSimulationTokenRequest
> = z.object({
  id: z.string(),
});

export function getSimulationTokenRequestToJSON(
  getSimulationTokenRequest: GetSimulationTokenRequest,
): string {
  return JSON.stringify(
    GetSimulationTokenRequest$outboundSchema.parse(getSimulationTokenRequest),
  );
}

/** @internal */
export const GetSimulationTokenResponse$inboundSchema: z.ZodMiniType<
  GetSimulationTokenResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CurrentSimulationToken$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getSimulationTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSimulationTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSimulationTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSimulationTokenResponse' from JSON`,
  );
}
