/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSimulationRequest = {
  /**
   * Stable Simulation ID.
   */
  id: string;
};

/** @internal */
export type GetSimulationRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSimulationRequest$outboundSchema: z.ZodMiniType<
  GetSimulationRequest$Outbound,
  GetSimulationRequest
> = z.object({
  id: z.string(),
});

export function getSimulationRequestToJSON(
  getSimulationRequest: GetSimulationRequest,
): string {
  return JSON.stringify(
    GetSimulationRequest$outboundSchema.parse(getSimulationRequest),
  );
}
