/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCredentialRequest = {
  /**
   * Credential ID.
   */
  id: string;
};

/** @internal */
export type GetCredentialRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCredentialRequest$outboundSchema: z.ZodMiniType<
  GetCredentialRequest$Outbound,
  GetCredentialRequest
> = z.object({
  id: z.string(),
});

export function getCredentialRequestToJSON(
  getCredentialRequest: GetCredentialRequest,
): string {
  return JSON.stringify(
    GetCredentialRequest$outboundSchema.parse(getCredentialRequest),
  );
}
