/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSimulationAdvanceRequest = {
  /**
   * Simulation or World ID.
   */
  id: string;
  /**
   * Clock advance operation ID.
   */
  advanceId: string;
};

/** @internal */
export type GetSimulationAdvanceRequest$Outbound = {
  id: string;
  advance_id: string;
};

/** @internal */
export const GetSimulationAdvanceRequest$outboundSchema: z.ZodMiniType<
  GetSimulationAdvanceRequest$Outbound,
  GetSimulationAdvanceRequest
> = z.pipe(
  z.object({
    id: z.string(),
    advanceId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      advanceId: "advance_id",
    });
  }),
);

export function getSimulationAdvanceRequestToJSON(
  getSimulationAdvanceRequest: GetSimulationAdvanceRequest,
): string {
  return JSON.stringify(
    GetSimulationAdvanceRequest$outboundSchema.parse(
      getSimulationAdvanceRequest,
    ),
  );
}
