/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetWorldRequest = {
  /**
   * World ID.
   */
  id: string;
};

/** @internal */
export type GetWorldRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWorldRequest$outboundSchema: z.ZodMiniType<
  GetWorldRequest$Outbound,
  GetWorldRequest
> = z.object({
  id: z.string(),
});

export function getWorldRequestToJSON(
  getWorldRequest: GetWorldRequest,
): string {
  return JSON.stringify(GetWorldRequest$outboundSchema.parse(getWorldRequest));
}
