/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetWorldAdvanceRequest = {
  /**
   * Simulation or World ID.
   */
  id: string;
  /**
   * Clock advance operation ID.
   */
  advanceId: string;
};

/** @internal */
export type GetWorldAdvanceRequest$Outbound = {
  id: string;
  advance_id: string;
};

/** @internal */
export const GetWorldAdvanceRequest$outboundSchema: z.ZodMiniType<
  GetWorldAdvanceRequest$Outbound,
  GetWorldAdvanceRequest
> = z.pipe(
  z.object({
    id: z.string(),
    advanceId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      advanceId: "advance_id",
    });
  }),
);

export function getWorldAdvanceRequestToJSON(
  getWorldAdvanceRequest: GetWorldAdvanceRequest,
): string {
  return JSON.stringify(
    GetWorldAdvanceRequest$outboundSchema.parse(getWorldAdvanceRequest),
  );
}
