/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListSimulationStepsRequest = {
  /**
   * Stable Simulation ID.
   */
  id: string;
  /**
   * Opaque next_cursor value from a previous page.
   */
  cursor?: string | undefined;
  /**
   * Page size. Values below 1 use 50. Values above 200 use 200.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListSimulationStepsRequest$Outbound = {
  id: string;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListSimulationStepsRequest$outboundSchema: z.ZodMiniType<
  ListSimulationStepsRequest$Outbound,
  ListSimulationStepsRequest
> = z.object({
  id: z.string(),
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 50),
});

export function listSimulationStepsRequestToJSON(
  listSimulationStepsRequest: ListSimulationStepsRequest,
): string {
  return JSON.stringify(
    ListSimulationStepsRequest$outboundSchema.parse(listSimulationStepsRequest),
  );
}
