/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListSimulationAdvanceEventsRequest = {
  /**
   * Simulation ID.
   */
  id: string;
  /**
   * Advance ID. A historical fork can read inherited runtime receipts.
   */
  advanceId: string;
  /**
   * Cursor from the previous page.
   */
  cursor?: string | undefined;
  /**
   * Page size, up to 200.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListSimulationAdvanceEventsRequest$Outbound = {
  id: string;
  advance_id: string;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListSimulationAdvanceEventsRequest$outboundSchema: z.ZodMiniType<
  ListSimulationAdvanceEventsRequest$Outbound,
  ListSimulationAdvanceEventsRequest
> = z.pipe(
  z.object({
    id: z.string(),
    advanceId: z.string(),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
  }),
  z.transform((v) => {
    return remap$(v, {
      advanceId: "advance_id",
    });
  }),
);

export function listSimulationAdvanceEventsRequestToJSON(
  listSimulationAdvanceEventsRequest: ListSimulationAdvanceEventsRequest,
): string {
  return JSON.stringify(
    ListSimulationAdvanceEventsRequest$outboundSchema.parse(
      listSimulationAdvanceEventsRequest,
    ),
  );
}
