/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListCredentialsRequest = {
  /**
   * Page size. Values below 1 use 50. Values above 200 use 200.
   */
  limit?: number | undefined;
  /**
   * Opaque next_cursor value from a previous page.
   */
  cursor?: string | undefined;
};

/** @internal */
export type ListCredentialsRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListCredentialsRequest$outboundSchema: z.ZodMiniType<
  ListCredentialsRequest$Outbound,
  ListCredentialsRequest
> = z.object({
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listCredentialsRequestToJSON(
  listCredentialsRequest: ListCredentialsRequest,
): string {
  return JSON.stringify(
    ListCredentialsRequest$outboundSchema.parse(listCredentialsRequest),
  );
}
