/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Optional status filter.
 */
export const ListWorldsStatus = {
  Pending: "pending",
  Building: "building",
  Ready: "ready",
  Running: "running",
  Stopped: "stopped",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * Optional status filter.
 */
export type ListWorldsStatus = ClosedEnum<typeof ListWorldsStatus>;

export type ListWorldsRequest = {
  /**
   * Optional status filter.
   */
  status?: ListWorldsStatus | undefined;
  /**
   * Page size. Values below 1 use 50. Values above 200 use 200.
   */
  limit?: number | undefined;
  /**
   * Opaque next_cursor value from a previous page.
   */
  cursor?: string | undefined;
};

/** @internal */
export const ListWorldsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListWorldsStatus
> = z.enum(ListWorldsStatus);

/** @internal */
export type ListWorldsRequest$Outbound = {
  status?: string | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListWorldsRequest$outboundSchema: z.ZodMiniType<
  ListWorldsRequest$Outbound,
  ListWorldsRequest
> = z.object({
  status: z.optional(ListWorldsStatus$outboundSchema),
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listWorldsRequestToJSON(
  listWorldsRequest: ListWorldsRequest,
): string {
  return JSON.stringify(
    ListWorldsRequest$outboundSchema.parse(listWorldsRequest),
  );
}
