/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Optional build status filter.
 */
export const ListSimulatorsStatus = {
  Building: "building",
  Ready: "ready",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * Optional build status filter.
 */
export type ListSimulatorsStatus = ClosedEnum<typeof ListSimulatorsStatus>;

export type ListSimulatorsRequest = {
  /**
   * Optional build status filter.
   */
  status?: ListSimulatorsStatus | undefined;
  /**
   * Optional exact Simulator name. Prefix a catalog name with continuous/. Names cannot start with smr_.
   */
  name?: string | undefined;
  /**
   * Page size. Values below 1 use 50. Values above 200 use 200.
   */
  limit?: number | undefined;
  /**
   * Opaque next_cursor value from a previous page.
   */
  cursor?: string | undefined;
};

/** @internal */
export const ListSimulatorsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListSimulatorsStatus
> = z.enum(ListSimulatorsStatus);

/** @internal */
export type ListSimulatorsRequest$Outbound = {
  status?: string | undefined;
  name?: string | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListSimulatorsRequest$outboundSchema: z.ZodMiniType<
  ListSimulatorsRequest$Outbound,
  ListSimulatorsRequest
> = z.object({
  status: z.optional(ListSimulatorsStatus$outboundSchema),
  name: z.optional(z.string()),
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listSimulatorsRequestToJSON(
  listSimulatorsRequest: ListSimulatorsRequest,
): string {
  return JSON.stringify(
    ListSimulatorsRequest$outboundSchema.parse(listSimulatorsRequest),
  );
}
