/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListWorldsRequest = {
  /**
   * Page size. Values below 1 use 50. Values above 200 use 200.
   */
  limit?: number | undefined;
  /**
   * Opaque cursor from the previous page.
   */
  cursor?: string | undefined;
};

/** @internal */
export type ListWorldsRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListWorldsRequest$outboundSchema: z.ZodMiniType<
  ListWorldsRequest$Outbound,
  ListWorldsRequest
> = z.object({
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listWorldsRequestToJSON(
  listWorldsRequest: ListWorldsRequest,
): string {
  return JSON.stringify(
    ListWorldsRequest$outboundSchema.parse(listWorldsRequest),
  );
}
