/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Optional lifecycle status filter.
 */
export const ListSimulationsStatus = {
  Running: "running",
  Paused: "paused",
  Stopped: "stopped",
} as const;
/**
 * Optional lifecycle status filter.
 */
export type ListSimulationsStatus = ClosedEnum<typeof ListSimulationsStatus>;

export type ListSimulationsRequest = {
  /**
   * Optional lifecycle status filter.
   */
  status?: ListSimulationsStatus | undefined;
  /**
   * Optional stable Simulator ID filter.
   */
  simulatorId?: string | undefined;
  /**
   * Page size. Values below 1 use 50. Values above 200 use 200.
   */
  limit?: number | undefined;
  /**
   * Opaque next_cursor value from a previous page.
   */
  cursor?: string | undefined;
};

/** @internal */
export const ListSimulationsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListSimulationsStatus
> = z.enum(ListSimulationsStatus);

/** @internal */
export type ListSimulationsRequest$Outbound = {
  status?: string | undefined;
  simulator_id?: string | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListSimulationsRequest$outboundSchema: z.ZodMiniType<
  ListSimulationsRequest$Outbound,
  ListSimulationsRequest
> = z.pipe(
  z.object({
    status: z.optional(ListSimulationsStatus$outboundSchema),
    simulatorId: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    cursor: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      simulatorId: "simulator_id",
    });
  }),
);

export function listSimulationsRequestToJSON(
  listSimulationsRequest: ListSimulationsRequest,
): string {
  return JSON.stringify(
    ListSimulationsRequest$outboundSchema.parse(listSimulationsRequest),
  );
}
