/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type MintSimulationTokenRequest = {
  /**
   * Stable Simulation ID.
   */
  id: string;
  body: models.MintSimulationTokenRequest;
};

/** @internal */
export type MintSimulationTokenRequest$Outbound = {
  id: string;
  body: models.MintSimulationTokenRequest$Outbound;
};

/** @internal */
export const MintSimulationTokenRequest$outboundSchema: z.ZodMiniType<
  MintSimulationTokenRequest$Outbound,
  MintSimulationTokenRequest
> = z.object({
  id: z.string(),
  body: models.MintSimulationTokenRequest$outboundSchema,
});

export function mintSimulationTokenRequestToJSON(
  mintSimulationTokenRequest: MintSimulationTokenRequest,
): string {
  return JSON.stringify(
    MintSimulationTokenRequest$outboundSchema.parse(mintSimulationTokenRequest),
  );
}
