/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RegenerateSimulationTokenRequest = {
  /**
   * Simulation ID.
   */
  id: string;
  /**
   * Stable key for this regeneration request.
   */
  idempotencyKey: string;
};

export type RegenerateSimulationTokenResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CurrentSimulationToken;
};

/** @internal */
export type RegenerateSimulationTokenRequest$Outbound = {
  id: string;
  "Idempotency-Key": string;
};

/** @internal */
export const RegenerateSimulationTokenRequest$outboundSchema: z.ZodMiniType<
  RegenerateSimulationTokenRequest$Outbound,
  RegenerateSimulationTokenRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function regenerateSimulationTokenRequestToJSON(
  regenerateSimulationTokenRequest: RegenerateSimulationTokenRequest,
): string {
  return JSON.stringify(
    RegenerateSimulationTokenRequest$outboundSchema.parse(
      regenerateSimulationTokenRequest,
    ),
  );
}

/** @internal */
export const RegenerateSimulationTokenResponse$inboundSchema: z.ZodMiniType<
  RegenerateSimulationTokenResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CurrentSimulationToken$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function regenerateSimulationTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<RegenerateSimulationTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegenerateSimulationTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegenerateSimulationTokenResponse' from JSON`,
  );
}
