/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type StartSimulationRequest = {
  /**
   * Simulation ID.
   */
  id: string;
};

export type StartSimulationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatedSimulation;
};

/** @internal */
export type StartSimulationRequest$Outbound = {
  id: string;
};

/** @internal */
export const StartSimulationRequest$outboundSchema: z.ZodMiniType<
  StartSimulationRequest$Outbound,
  StartSimulationRequest
> = z.object({
  id: z.string(),
});

export function startSimulationRequestToJSON(
  startSimulationRequest: StartSimulationRequest,
): string {
  return JSON.stringify(
    StartSimulationRequest$outboundSchema.parse(startSimulationRequest),
  );
}

/** @internal */
export const StartSimulationResponse$inboundSchema: z.ZodMiniType<
  StartSimulationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.CreatedSimulation$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function startSimulationResponseFromJSON(
  jsonString: string,
): SafeParseResult<StartSimulationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StartSimulationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StartSimulationResponse' from JSON`,
  );
}
