/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type StartWorldRequest = {
  /**
   * Stable World ID.
   */
  id: string;
};

/** @internal */
export type StartWorldRequest$Outbound = {
  id: string;
};

/** @internal */
export const StartWorldRequest$outboundSchema: z.ZodMiniType<
  StartWorldRequest$Outbound,
  StartWorldRequest
> = z.object({
  id: z.string(),
});

export function startWorldRequestToJSON(
  startWorldRequest: StartWorldRequest,
): string {
  return JSON.stringify(
    StartWorldRequest$outboundSchema.parse(startWorldRequest),
  );
}
