/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type StartWorldRequest = {
  /**
   * World ID.
   */
  id: string;
  body?: models.StartWorldRequest | undefined;
};

/** @internal */
export type StartWorldRequest$Outbound = {
  id: string;
  body?: models.StartWorldRequest$Outbound | undefined;
};

/** @internal */
export const StartWorldRequest$outboundSchema: z.ZodMiniType<
  StartWorldRequest$Outbound,
  StartWorldRequest
> = z.object({
  id: z.string(),
  body: z.optional(models.StartWorldRequest$outboundSchema),
});

export function startWorldRequestToJSON(
  startWorldRequest: StartWorldRequest,
): string {
  return JSON.stringify(
    StartWorldRequest$outboundSchema.parse(startWorldRequest),
  );
}
