/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type StartSimulationRequest = {
  /**
   * Stable Simulation ID.
   */
  id: string;
};

/** @internal */
export type StartSimulationRequest$Outbound = {
  id: string;
};

/** @internal */
export const StartSimulationRequest$outboundSchema: z.ZodMiniType<
  StartSimulationRequest$Outbound,
  StartSimulationRequest
> = z.object({
  id: z.string(),
});

export function startSimulationRequestToJSON(
  startSimulationRequest: StartSimulationRequest,
): string {
  return JSON.stringify(
    StartSimulationRequest$outboundSchema.parse(startSimulationRequest),
  );
}
