/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type StopWorldRequest = {
  /**
   * Stable World ID.
   */
  id: string;
};

/** @internal */
export type StopWorldRequest$Outbound = {
  id: string;
};

/** @internal */
export const StopWorldRequest$outboundSchema: z.ZodMiniType<
  StopWorldRequest$Outbound,
  StopWorldRequest
> = z.object({
  id: z.string(),
});

export function stopWorldRequestToJSON(
  stopWorldRequest: StopWorldRequest,
): string {
  return JSON.stringify(
    StopWorldRequest$outboundSchema.parse(stopWorldRequest),
  );
}
