/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type StopSimulationRequest = {
  /**
   * Simulation ID.
   */
  id: string;
};

/** @internal */
export type StopSimulationRequest$Outbound = {
  id: string;
};

/** @internal */
export const StopSimulationRequest$outboundSchema: z.ZodMiniType<
  StopSimulationRequest$Outbound,
  StopSimulationRequest
> = z.object({
  id: z.string(),
});

export function stopSimulationRequestToJSON(
  stopSimulationRequest: StopSimulationRequest,
): string {
  return JSON.stringify(
    StopSimulationRequest$outboundSchema.parse(stopSimulationRequest),
  );
}
