/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateCredentialRequest = {
  /**
   * Credential ID.
   */
  id: string;
  body: models.UpdateCredentialRequest;
};

/** @internal */
export type UpdateCredentialRequest$Outbound = {
  id: string;
  body: models.UpdateCredentialRequest$Outbound;
};

/** @internal */
export const UpdateCredentialRequest$outboundSchema: z.ZodMiniType<
  UpdateCredentialRequest$Outbound,
  UpdateCredentialRequest
> = z.object({
  id: z.string(),
  body: models.UpdateCredentialRequest$outboundSchema,
});

export function updateCredentialRequestToJSON(
  updateCredentialRequest: UpdateCredentialRequest,
): string {
  return JSON.stringify(
    UpdateCredentialRequest$outboundSchema.parse(updateCredentialRequest),
  );
}
