/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AdvanceTimeRequest = {
  /**
   * Absolute target time in RFC 3339, with at most millisecond precision.
   */
  to: Date;
};

/** @internal */
export type AdvanceTimeRequest$Outbound = {
  to: string;
};

/** @internal */
export const AdvanceTimeRequest$outboundSchema: z.ZodMiniType<
  AdvanceTimeRequest$Outbound,
  AdvanceTimeRequest
> = z.object({
  to: z.pipe(z.date(), z.transform(v => v.toISOString())),
});

export function advanceTimeRequestToJSON(
  advanceTimeRequest: AdvanceTimeRequest,
): string {
  return JSON.stringify(
    AdvanceTimeRequest$outboundSchema.parse(advanceTimeRequest),
  );
}
