/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AdvanceTimeInputBody = {
  /**
   * Absolute target time in RFC 3339, with at most millisecond precision.
   */
  to: Date;
};

/** @internal */
export type AdvanceTimeInputBody$Outbound = {
  to: string;
};

/** @internal */
export const AdvanceTimeInputBody$outboundSchema: z.ZodMiniType<
  AdvanceTimeInputBody$Outbound,
  AdvanceTimeInputBody
> = z.object({
  to: z.pipe(z.date(), z.transform(v => v.toISOString())),
});

export function advanceTimeInputBodyToJSON(
  advanceTimeInputBody: AdvanceTimeInputBody,
): string {
  return JSON.stringify(
    AdvanceTimeInputBody$outboundSchema.parse(advanceTimeInputBody),
  );
}
