/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type BuildToolCall = {
  /**
   * Time the call ran.
   */
  at: Date;
  /**
   * Name of the tool. Arguments and output are private.
   */
  tool: string;
};

/** @internal */
export const BuildToolCall$inboundSchema: z.ZodMiniType<
  BuildToolCall,
  unknown
> = z.object({
  at: types.date(),
  tool: types.string(),
});

export function buildToolCallFromJSON(
  jsonString: string,
): SafeParseResult<BuildToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuildToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuildToolCall' from JSON`,
  );
}
