/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Model provider that builds starting data. Defaults to claude.
 */
export const BuildWorldRequestBuilder = {
  Openai: "openai",
  Claude: "claude",
} as const;
/**
 * Model provider that builds starting data. Defaults to claude.
 */
export type BuildWorldRequestBuilder = ClosedEnum<
  typeof BuildWorldRequestBuilder
>;

export type BuildWorldRequest = {
  /**
   * Model provider that builds starting data. Defaults to claude.
   */
  builder?: BuildWorldRequestBuilder | undefined;
  /**
   * Describe the initial data, scenario, and relationships. Populated Worlds support up to 8 selected Simulators and 1,000 starting records in total. Named record types replace their default data. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted.
   */
  instructions?: string | undefined;
  /**
   * Name for the World. Omission generates a name. The ID stays its identity, and names need not be unique.
   */
  name?: string | undefined;
  /**
   * Simulator IDs for the World.
   */
  simulators: Array<string>;
  /**
   * Simulated time the World starts at, in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Saved starting data keeps its build dates.
   */
  startTime?: Date | undefined;
  /**
   * Time limit for generation and validation in seconds, from 1 to 43200. Defaults to 3600 (one hour). Excludes queue wait and finalization. Retries share the same deadline.
   */
  timeoutSeconds?: number | undefined;
};

/** @internal */
export const BuildWorldRequestBuilder$outboundSchema: z.ZodMiniEnum<
  typeof BuildWorldRequestBuilder
> = z.enum(BuildWorldRequestBuilder);

/** @internal */
export type BuildWorldRequest$Outbound = {
  builder: string;
  instructions?: string | undefined;
  name?: string | undefined;
  simulators: Array<string>;
  start_time?: string | undefined;
  timeout_seconds: number;
};

/** @internal */
export const BuildWorldRequest$outboundSchema: z.ZodMiniType<
  BuildWorldRequest$Outbound,
  BuildWorldRequest
> = z.pipe(
  z.object({
    builder: z._default(BuildWorldRequestBuilder$outboundSchema, "claude"),
    instructions: z.optional(z.string()),
    name: z.optional(z.string()),
    simulators: z.array(z.string()),
    startTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    timeoutSeconds: z._default(z.int(), 3600),
  }),
  z.transform((v) => {
    return remap$(v, {
      startTime: "start_time",
      timeoutSeconds: "timeout_seconds",
    });
  }),
);

export function buildWorldRequestToJSON(
  buildWorldRequest: BuildWorldRequest,
): string {
  return JSON.stringify(
    BuildWorldRequest$outboundSchema.parse(buildWorldRequest),
  );
}
