/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Model that builds and reviews starting data. Defaults to gpt-6-astra. Its provider is derived from the model.
 */
export const BuildWorldRequestModel = {
  Gpt6Astra: "gpt-6-astra",
  Gpt6Sol: "gpt-6-sol",
  ClaudeOpus55: "claude-opus-5-5",
  ClaudeFable51: "claude-fable-5-1",
} as const;
/**
 * Model that builds and reviews starting data. Defaults to gpt-6-astra. Its provider is derived from the model.
 */
export type BuildWorldRequestModel = ClosedEnum<typeof BuildWorldRequestModel>;

export type BuildWorldRequest = {
  /**
   * Describe the initial data, scenario, and relationships. Populated Worlds support up to 8 selected Simulators and 1,000 starting records in total. Named record types replace their default data. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted.
   */
  instructions?: string | undefined;
  /**
   * Customer JSON metadata, up to 16 KiB and 64 nesting levels. Returned by build, get, and list. Omission uses null.
   */
  metadata?: any | undefined;
  /**
   * Model that builds and reviews starting data. Defaults to gpt-6-astra. Its provider is derived from the model.
   */
  model?: BuildWorldRequestModel | undefined;
  /**
   * Name for the World. Omission generates a name. The ID stays its identity, and names need not be unique.
   */
  name?: string | undefined;
  /**
   * Simulator IDs for the World.
   */
  simulators: Array<string>;
  /**
   * Simulated time the World starts at, in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Saved starting data keeps its build dates.
   */
  startTime?: Date | undefined;
  /**
   * Time limit for generation and validation in seconds, from 1 to 72000. Defaults to 14400 (four hours). Excludes queue wait and finalization. Retries share the same deadline.
   */
  timeoutSeconds?: number | undefined;
};

/** @internal */
export const BuildWorldRequestModel$outboundSchema: z.ZodMiniEnum<
  typeof BuildWorldRequestModel
> = z.enum(BuildWorldRequestModel);

/** @internal */
export type BuildWorldRequest$Outbound = {
  instructions?: string | undefined;
  metadata?: any | undefined;
  model: string;
  name?: string | undefined;
  simulators: Array<string>;
  start_time?: string | undefined;
  timeout_seconds: number;
};

/** @internal */
export const BuildWorldRequest$outboundSchema: z.ZodMiniType<
  BuildWorldRequest$Outbound,
  BuildWorldRequest
> = z.pipe(
  z.object({
    instructions: z.optional(z.string()),
    metadata: z.optional(z.any()),
    model: z._default(BuildWorldRequestModel$outboundSchema, "gpt-6-astra"),
    name: z.optional(z.string()),
    simulators: z.array(z.string()),
    startTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    timeoutSeconds: z._default(z.int(), 14400),
  }),
  z.transform((v) => {
    return remap$(v, {
      startTime: "start_time",
      timeoutSeconds: "timeout_seconds",
    });
  }),
);

export function buildWorldRequestToJSON(
  buildWorldRequest: BuildWorldRequest,
): string {
  return JSON.stringify(
    BuildWorldRequest$outboundSchema.parse(buildWorldRequest),
  );
}
