/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Legacy provider selection. Alone it selects the provider's default model (openai is gpt-6-astra, claude is claude-fable-5-1); with model it must name the model's provider.
 */
export const BuildSimulatorRequestBuilder = {
  Openai: "openai",
  Claude: "claude",
} as const;
/**
 * Legacy provider selection. Alone it selects the provider's default model (openai is gpt-6-astra, claude is claude-fable-5-1); with model it must name the model's provider.
 */
export type BuildSimulatorRequestBuilder = ClosedEnum<
  typeof BuildSimulatorRequestBuilder
>;

/**
 * Model that builds and reviews the Simulator. Defaults to gpt-6-astra. Its provider is derived from the model.
 */
export const BuildSimulatorRequestModel = {
  Gpt6Astra: "gpt-6-astra",
  Gpt6Sol: "gpt-6-sol",
  ClaudeOpus55: "claude-opus-5-5",
  ClaudeFable51: "claude-fable-5-1",
} as const;
/**
 * Model that builds and reviews the Simulator. Defaults to gpt-6-astra. Its provider is derived from the model.
 */
export type BuildSimulatorRequestModel = ClosedEnum<
  typeof BuildSimulatorRequestModel
>;

/**
 * Source specification format. Omission detects the format.
 */
export const BuildSimulatorRequestSpecKind = {
  Openapi: "openapi",
  Wsdl: "wsdl",
} as const;
/**
 * Source specification format. Omission detects the format.
 */
export type BuildSimulatorRequestSpecKind = ClosedEnum<
  typeof BuildSimulatorRequestSpecKind
>;

export type BuildSimulatorRequest = {
  /**
   * Legacy provider selection. Alone it selects the provider's default model (openai is gpt-6-astra, claude is claude-fable-5-1); with model it must name the model's provider.
   */
  builder?: BuildSimulatorRequestBuilder | undefined;
  /**
   * Regular expressions (RE2 syntax) that select the operations to implement. Each is matched against the OpenAPI operationId or the WSDL operation name; an operation is kept when any expression matches, and an OpenAPI operation without an operationId is dropped. At most 64 expressions of at most 1,024 characters each. Omit or send an empty list to keep every operation. Not allowed for an incremental build.
   */
  filter?: Array<string> | undefined;
  /**
   * Instructions for the builder. Required for an incremental build. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000.
   */
  instructions?: string | undefined;
  /**
   * Model that builds and reviews the Simulator. Defaults to gpt-6-astra. Its provider is derived from the model.
   */
  model?: BuildSimulatorRequestModel | undefined;
  /**
   * Name for the Simulator. Omission generates a name. Names must not contain U+0000. The ID stays its identity, and names need not be unique.
   */
  name?: string | undefined;
  /**
   * Parent Simulator ID. With instructions and no spec this starts an incremental build: the parent must be ready, and the request takes no filter or spec_kind.
   */
  parentId?: string | undefined;
  /**
   * Source specification format. Omission detects the format.
   */
  specKind?: BuildSimulatorRequestSpecKind | undefined;
  /**
   * Time limit for generation and validation in seconds, from 1 to 72000. Defaults to 14400 (four hours). Excludes queue wait and finalization. Retries share the same deadline.
   */
  timeoutSeconds?: number | undefined;
};

/** @internal */
export const BuildSimulatorRequestBuilder$outboundSchema: z.ZodMiniEnum<
  typeof BuildSimulatorRequestBuilder
> = z.enum(BuildSimulatorRequestBuilder);

/** @internal */
export const BuildSimulatorRequestModel$outboundSchema: z.ZodMiniEnum<
  typeof BuildSimulatorRequestModel
> = z.enum(BuildSimulatorRequestModel);

/** @internal */
export const BuildSimulatorRequestSpecKind$outboundSchema: z.ZodMiniEnum<
  typeof BuildSimulatorRequestSpecKind
> = z.enum(BuildSimulatorRequestSpecKind);

/** @internal */
export type BuildSimulatorRequest$Outbound = {
  builder?: string | undefined;
  filter?: Array<string> | undefined;
  instructions?: string | undefined;
  model: string;
  name?: string | undefined;
  parent_id?: string | undefined;
  spec_kind?: string | undefined;
  timeout_seconds: number;
};

/** @internal */
export const BuildSimulatorRequest$outboundSchema: z.ZodMiniType<
  BuildSimulatorRequest$Outbound,
  BuildSimulatorRequest
> = z.pipe(
  z.object({
    builder: z.optional(BuildSimulatorRequestBuilder$outboundSchema),
    filter: z.optional(z.array(z.string())),
    instructions: z.optional(z.string()),
    model: z._default(BuildSimulatorRequestModel$outboundSchema, "gpt-6-astra"),
    name: z.optional(z.string()),
    parentId: z.optional(z.string()),
    specKind: z.optional(BuildSimulatorRequestSpecKind$outboundSchema),
    timeoutSeconds: z._default(z.int(), 14400),
  }),
  z.transform((v) => {
    return remap$(v, {
      parentId: "parent_id",
      specKind: "spec_kind",
      timeoutSeconds: "timeout_seconds",
    });
  }),
);

export function buildSimulatorRequestToJSON(
  buildSimulatorRequest: BuildSimulatorRequest,
): string {
  return JSON.stringify(
    BuildSimulatorRequest$outboundSchema.parse(buildSimulatorRequest),
  );
}
