/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Builder provider. The default is claude.
 */
export const Builder = {
  Openai: "openai",
  Claude: "claude",
} as const;
/**
 * Builder provider. The default is claude.
 */
export type Builder = ClosedEnum<typeof Builder>;

/**
 * Source specification format. Omission detects the format.
 */
export const SpecKind = {
  Openapi: "openapi",
  Wsdl: "wsdl",
} as const;
/**
 * Source specification format. Omission detects the format.
 */
export type SpecKind = ClosedEnum<typeof SpecKind>;

export type BuildSimulatorRequest = {
  /**
   * Builder provider. The default is claude.
   */
  builder?: Builder | undefined;
  /**
   * Optional operation filter regular expressions. Supply at most 64 expressions, with 1,024 characters in each expression. An empty list keeps all operations.
   */
  filter?: Array<string> | undefined;
  /**
   * Build guidance. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted.
   */
  instructions?: string | undefined;
  /**
   * Optional Simulator name. Names cannot start with smr_. Omission generates a name.
   */
  name?: string | undefined;
  /**
   * Stable parent Simulator ID for an incremental build.
   */
  parentId?: string | undefined;
  /**
   * Source specification format. Omission detects the format.
   */
  specKind?: SpecKind | undefined;
};

/** @internal */
export const Builder$outboundSchema: z.ZodMiniEnum<typeof Builder> = z.enum(
  Builder,
);

/** @internal */
export const SpecKind$outboundSchema: z.ZodMiniEnum<typeof SpecKind> = z.enum(
  SpecKind,
);

/** @internal */
export type BuildSimulatorRequest$Outbound = {
  builder: string;
  filter?: Array<string> | undefined;
  instructions?: string | undefined;
  name?: string | undefined;
  parent_id?: string | undefined;
  spec_kind?: string | undefined;
};

/** @internal */
export const BuildSimulatorRequest$outboundSchema: z.ZodMiniType<
  BuildSimulatorRequest$Outbound,
  BuildSimulatorRequest
> = z.pipe(
  z.object({
    builder: z._default(Builder$outboundSchema, "claude"),
    filter: z.optional(z.array(z.string())),
    instructions: z.optional(z.string()),
    name: z.optional(z.string()),
    parentId: z.optional(z.string()),
    specKind: z.optional(SpecKind$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      parentId: "parent_id",
      specKind: "spec_kind",
    });
  }),
);

export function buildSimulatorRequestToJSON(
  buildSimulatorRequest: BuildSimulatorRequest,
): string {
  return JSON.stringify(
    BuildSimulatorRequest$outboundSchema.parse(buildSimulatorRequest),
  );
}
