/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Model provider that builds the Simulator. Defaults to claude.
 */
export const BuildSimulatorRequestBuilder = {
  Openai: "openai",
  Claude: "claude",
} as const;
/**
 * Model provider that builds the Simulator. Defaults to claude.
 */
export type BuildSimulatorRequestBuilder = ClosedEnum<
  typeof BuildSimulatorRequestBuilder
>;

/**
 * Source specification format. Omission detects the format.
 */
export const SpecKind = {
  Openapi: "openapi",
  Wsdl: "wsdl",
} as const;
/**
 * Source specification format. Omission detects the format.
 */
export type SpecKind = ClosedEnum<typeof SpecKind>;

export type BuildSimulatorRequest = {
  /**
   * Model provider that builds the Simulator. Defaults to claude.
   */
  builder?: BuildSimulatorRequestBuilder | undefined;
  /**
   * Regular expressions (RE2 syntax) that select the operations to implement. Each is matched against the OpenAPI operationId or the WSDL operation name; an operation is kept when any expression matches, and an OpenAPI operation without an operationId is dropped. At most 64 expressions of at most 1,024 characters each. Omit or send an empty list to keep every operation. Not allowed for an incremental build.
   */
  filter?: Array<string> | undefined;
  /**
   * Instructions for the builder. Required for an incremental build. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000.
   */
  instructions?: string | undefined;
  /**
   * Optional Simulator name. Names cannot start with smr_. Omission generates a name.
   */
  name?: string | undefined;
  /**
   * Parent Simulator ID. With instructions and no spec this starts an incremental build: the parent must be ready, and the request takes no filter or spec_kind.
   */
  parentId?: string | undefined;
  /**
   * Source specification format. Omission detects the format.
   */
  specKind?: SpecKind | undefined;
};

/** @internal */
export const BuildSimulatorRequestBuilder$outboundSchema: z.ZodMiniEnum<
  typeof BuildSimulatorRequestBuilder
> = z.enum(BuildSimulatorRequestBuilder);

/** @internal */
export const SpecKind$outboundSchema: z.ZodMiniEnum<typeof SpecKind> = z.enum(
  SpecKind,
);

/** @internal */
export type BuildSimulatorRequest$Outbound = {
  builder: string;
  filter?: Array<string> | undefined;
  instructions?: string | undefined;
  name?: string | undefined;
  parent_id?: string | undefined;
  spec_kind?: string | undefined;
};

/** @internal */
export const BuildSimulatorRequest$outboundSchema: z.ZodMiniType<
  BuildSimulatorRequest$Outbound,
  BuildSimulatorRequest
> = z.pipe(
  z.object({
    builder: z._default(BuildSimulatorRequestBuilder$outboundSchema, "claude"),
    filter: z.optional(z.array(z.string())),
    instructions: z.optional(z.string()),
    name: z.optional(z.string()),
    parentId: z.optional(z.string()),
    specKind: z.optional(SpecKind$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      parentId: "parent_id",
      specKind: "spec_kind",
    });
  }),
);

export function buildSimulatorRequestToJSON(
  buildSimulatorRequest: BuildSimulatorRequest,
): string {
  return JSON.stringify(
    BuildSimulatorRequest$outboundSchema.parse(buildSimulatorRequest),
  );
}
