/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type BuildWorldRequest = {
  /**
   * Build guidance. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted.
   */
  instructions?: string | undefined;
  /**
   * Stable Simulator IDs for the World.
   */
  simulators: Array<string>;
};

/** @internal */
export type BuildWorldRequest$Outbound = {
  instructions?: string | undefined;
  simulators: Array<string>;
};

/** @internal */
export const BuildWorldRequest$outboundSchema: z.ZodMiniType<
  BuildWorldRequest$Outbound,
  BuildWorldRequest
> = z.object({
  instructions: z.optional(z.string()),
  simulators: z.array(z.string()),
});

export function buildWorldRequestToJSON(
  buildWorldRequest: BuildWorldRequest,
): string {
  return JSON.stringify(
    BuildWorldRequest$outboundSchema.parse(buildWorldRequest),
  );
}
