/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ClockEvent = {
  /**
   * Simulated time observed by this event handler.
   */
  at: Date;
  /**
   * Scheduled event ID.
   */
  eventId: string;
  /**
   * Persisted insertion order for events due at the same time.
   */
  sequence: number;
  /**
   * Declared event type.
   */
  type: string;
};

/** @internal */
export const ClockEvent$inboundSchema: z.ZodMiniType<ClockEvent, unknown> = z
  .pipe(
    z.object({
      at: types.date(),
      event_id: types.string(),
      sequence: types.number(),
      type: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "event_id": "eventId",
      });
    }),
  );

export function clockEventFromJSON(
  jsonString: string,
): SafeParseResult<ClockEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClockEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClockEvent' from JSON`,
  );
}
