/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ClockAdvanceMember,
  ClockAdvanceMember$inboundSchema,
} from "./clock-advance-member.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ResourceError,
  ResourceError$inboundSchema,
} from "./resource-error.js";

/**
 * Durable operation state. Poll while pending or running.
 */
export const ClockAdvanceStatus = {
  Pending: "pending",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Durable operation state. Poll while pending or running.
 */
export type ClockAdvanceStatus = OpenEnum<typeof ClockAdvanceStatus>;

export type ClockAdvance = {
  error: ResourceError | null;
  /**
   * Number of committed event executions.
   */
  eventCount: number;
  /**
   * Clock before the requested advance.
   */
  from: Date;
  /**
   * Stable clock advance operation ID.
   */
  id: string;
  /**
   * Progress for each participating Simulation.
   */
  members: Array<ClockAdvanceMember>;
  /**
   * Durable operation state. Poll while pending or running.
   */
  status: ClockAdvanceStatus;
  /**
   * Committed local step, or null for no change or a World operation.
   */
  step: number | null;
  /**
   * Requested absolute target time.
   */
  to: Date;
};

/** @internal */
export const ClockAdvanceStatus$inboundSchema: z.ZodMiniType<
  ClockAdvanceStatus,
  unknown
> = openEnums.inboundSchema(ClockAdvanceStatus);

/** @internal */
export const ClockAdvance$inboundSchema: z.ZodMiniType<ClockAdvance, unknown> =
  z.pipe(
    z.object({
      error: types.nullable(ResourceError$inboundSchema),
      event_count: types.number(),
      from: types.date(),
      id: types.string(),
      members: z.array(ClockAdvanceMember$inboundSchema),
      status: ClockAdvanceStatus$inboundSchema,
      step: types.nullable(types.number()),
      to: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "event_count": "eventCount",
      });
    }),
  );

export function clockAdvanceFromJSON(
  jsonString: string,
): SafeParseResult<ClockAdvance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClockAdvance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClockAdvance' from JSON`,
  );
}
