/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ResourceError,
  ResourceError$inboundSchema,
} from "./resource-error.js";

/**
 * Whether this member is pending, committed, failed, or skipped because it is not running.
 */
export const ClockAdvanceMemberStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Skipped: "skipped",
} as const;
/**
 * Whether this member is pending, committed, failed, or skipped because it is not running.
 */
export type ClockAdvanceMemberStatus = OpenEnum<
  typeof ClockAdvanceMemberStatus
>;

export type ClockAdvanceMember = {
  error: ResourceError | null;
  /**
   * Number of committed event executions.
   */
  eventCount: number;
  /**
   * Member Simulation ID.
   */
  simulationId: string;
  /**
   * Whether this member is pending, committed, failed, or skipped because it is not running.
   */
  status: ClockAdvanceMemberStatus;
  /**
   * Committed local step, or null for no change or a failed advance.
   */
  step: number | null;
};

/** @internal */
export const ClockAdvanceMemberStatus$inboundSchema: z.ZodMiniType<
  ClockAdvanceMemberStatus,
  unknown
> = openEnums.inboundSchema(ClockAdvanceMemberStatus);

/** @internal */
export const ClockAdvanceMember$inboundSchema: z.ZodMiniType<
  ClockAdvanceMember,
  unknown
> = z.pipe(
  z.object({
    error: types.nullable(ResourceError$inboundSchema),
    event_count: types.number(),
    simulation_id: types.string(),
    status: ClockAdvanceMemberStatus$inboundSchema,
    step: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_count": "eventCount",
      "simulation_id": "simulationId",
    });
  }),
);

export function clockAdvanceMemberFromJSON(
  jsonString: string,
): SafeParseResult<ClockAdvanceMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClockAdvanceMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClockAdvanceMember' from JSON`,
  );
}
