/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CloneSimulatorRequest = {
  /**
   * Stable key for retrying this clone into the target workspace.
   */
  idempotencyKey: string;
  /**
   * Display name for the clone. Defaults to the source Simulator's name.
   */
  name?: string | undefined;
  /**
   * Workspace that receives the clone. It must differ from the source workspace.
   */
  targetWorkspaceId: string;
};

/** @internal */
export type CloneSimulatorRequest$Outbound = {
  idempotency_key: string;
  name?: string | undefined;
  target_workspace_id: string;
};

/** @internal */
export const CloneSimulatorRequest$outboundSchema: z.ZodMiniType<
  CloneSimulatorRequest$Outbound,
  CloneSimulatorRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    name: z.optional(z.string()),
    targetWorkspaceId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency_key",
      targetWorkspaceId: "target_workspace_id",
    });
  }),
);

export function cloneSimulatorRequestToJSON(
  cloneSimulatorRequest: CloneSimulatorRequest,
): string {
  return JSON.stringify(
    CloneSimulatorRequest$outboundSchema.parse(cloneSimulatorRequest),
  );
}
