/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CloneSimulatorResponse = {
  /**
   * OCI manifest digest, unchanged from the source.
   */
  digest: string;
  /**
   * New Simulator ID in the target workspace, or the same ID on an idempotent retry.
   */
  id: string;
  /**
   * Display name of the clone.
   */
  name: string;
  /**
   * Target workspace.
   */
  workspaceId: string;
};

/** @internal */
export const CloneSimulatorResponse$inboundSchema: z.ZodMiniType<
  CloneSimulatorResponse,
  unknown
> = z.pipe(
  z.object({
    digest: types.string(),
    id: types.string(),
    name: types.string(),
    workspace_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
    });
  }),
);

export function cloneSimulatorResponseFromJSON(
  jsonString: string,
): SafeParseResult<CloneSimulatorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CloneSimulatorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CloneSimulatorResponse' from JSON`,
  );
}
