/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateCredentialRequest = {
  /**
   * The https URL of the real system. Requests go to paths under it.
   */
  baseUrl: string;
  /**
   * The HTTP header that carries the value.
   */
  header?: string | undefined;
  /**
   * Credential name.
   */
  name: string;
  /**
   * The full header value, for example Bearer followed by a token. The API never returns it.
   */
  value: string;
};

/** @internal */
export type CreateCredentialRequest$Outbound = {
  base_url: string;
  header: string;
  name: string;
  value: string;
};

/** @internal */
export const CreateCredentialRequest$outboundSchema: z.ZodMiniType<
  CreateCredentialRequest$Outbound,
  CreateCredentialRequest
> = z.pipe(
  z.object({
    baseUrl: z.string(),
    header: z._default(z.string(), "Authorization"),
    name: z.string(),
    value: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      baseUrl: "base_url",
    });
  }),
);

export function createCredentialRequestToJSON(
  createCredentialRequest: CreateCredentialRequest,
): string {
  return JSON.stringify(
    CreateCredentialRequest$outboundSchema.parse(createCredentialRequest),
  );
}
