/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateSimulationRequest = {
  /**
   * Name for the Simulation. Omission generates a name. The ID stays its identity, and names need not be unique.
   */
  name?: string | undefined;
  /**
   * ID of the ready Simulator.
   */
  simulatorId: string;
  /**
   * Initial simulated time in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Precision is milliseconds.
   */
  startTime?: Date | undefined;
};

/** @internal */
export type CreateSimulationRequest$Outbound = {
  name?: string | undefined;
  simulator_id: string;
  start_time?: string | undefined;
};

/** @internal */
export const CreateSimulationRequest$outboundSchema: z.ZodMiniType<
  CreateSimulationRequest$Outbound,
  CreateSimulationRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    simulatorId: z.string(),
    startTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      simulatorId: "simulator_id",
      startTime: "start_time",
    });
  }),
);

export function createSimulationRequestToJSON(
  createSimulationRequest: CreateSimulationRequest,
): string {
  return JSON.stringify(
    CreateSimulationRequest$outboundSchema.parse(createSimulationRequest),
  );
}
