/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateSimulationRequest = {
  /**
   * Optional Simulation name. Omission generates a name.
   */
  name?: string | undefined;
  /**
   * ID of the ready Simulator.
   */
  simulatorId: string;
};

/** @internal */
export type CreateSimulationRequest$Outbound = {
  name?: string | undefined;
  simulator_id: string;
};

/** @internal */
export const CreateSimulationRequest$outboundSchema: z.ZodMiniType<
  CreateSimulationRequest$Outbound,
  CreateSimulationRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    simulatorId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      simulatorId: "simulator_id",
    });
  }),
);

export function createSimulationRequestToJSON(
  createSimulationRequest: CreateSimulationRequest,
): string {
  return JSON.stringify(
    CreateSimulationRequest$outboundSchema.parse(createSimulationRequest),
  );
}
