/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
 */
export const CreatedSimulationStatus = {
  Running: "running",
  Paused: "paused",
  Stopped: "stopped",
} as const;
/**
 * Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
 */
export type CreatedSimulationStatus = OpenEnum<typeof CreatedSimulationStatus>;

export type CreatedSimulation = {
  /**
   * Simulation creation time.
   */
  createdAt: Date;
  /**
   * Base URL for requests to the Simulation.
   */
  endpoint: string;
  /**
   * Token expiration time.
   */
  expiresAt: Date;
  /**
   * Simulation ID.
   */
  id: string;
  /**
   * Simulation name.
   */
  name: string;
  /**
   * Source Simulation ID for a fork, or null.
   */
  parentId: string | null;
  /**
   * ID of the Simulator.
   */
  simulatorId: string;
  /**
   * Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
   */
  status: CreatedSimulationStatus;
  /**
   * Token for requests to the Simulation endpoint. Send it in the X-Continuous-Simulation-Token header. It is returned only here; list and get omit it. Create more with POST /v1/simulations/{id}/tokens.
   */
  token: string;
};

/** @internal */
export const CreatedSimulationStatus$inboundSchema: z.ZodMiniType<
  CreatedSimulationStatus,
  unknown
> = openEnums.inboundSchema(CreatedSimulationStatus);

/** @internal */
export const CreatedSimulation$inboundSchema: z.ZodMiniType<
  CreatedSimulation,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    endpoint: types.string(),
    expires_at: types.date(),
    id: types.string(),
    name: types.string(),
    parent_id: types.nullable(types.string()),
    simulator_id: types.string(),
    status: CreatedSimulationStatus$inboundSchema,
    token: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "expires_at": "expiresAt",
      "parent_id": "parentId",
      "simulator_id": "simulatorId",
    });
  }),
);

export function createdSimulationFromJSON(
  jsonString: string,
): SafeParseResult<CreatedSimulation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatedSimulation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatedSimulation' from JSON`,
  );
}
