/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Credential = {
  /**
   * The https URL of the real system, or null for a credential created without one. A build can use only a credential with a base URL.
   */
  baseUrl: string | null;
  /**
   * Credential creation time.
   */
  createdAt: Date;
  /**
   * The HTTP header that carries the value.
   */
  header: string;
  /**
   * Credential ID.
   */
  id: string;
  /**
   * Credential name. Names need not be unique.
   */
  name: string;
};

/** @internal */
export const Credential$inboundSchema: z.ZodMiniType<Credential, unknown> = z
  .pipe(
    z.object({
      base_url: types.nullable(types.string()),
      created_at: types.date(),
      header: types.string(),
      id: types.string(),
      name: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "base_url": "baseUrl",
        "created_at": "createdAt",
      });
    }),
  );

export function credentialFromJSON(
  jsonString: string,
): SafeParseResult<Credential, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Credential$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Credential' from JSON`,
  );
}
