/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CurrentSimulationToken = {
  /**
   * Null for a lifetime credential.
   */
  expiresAt: Date | null;
  /**
   * Current Simulation endpoint credential.
   */
  token: string;
};

/** @internal */
export const CurrentSimulationToken$inboundSchema: z.ZodMiniType<
  CurrentSimulationToken,
  unknown
> = z.pipe(
  z.object({
    expires_at: types.nullable(types.date()),
    token: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "expires_at": "expiresAt",
    });
  }),
);

export function currentSimulationTokenFromJSON(
  jsonString: string,
): SafeParseResult<CurrentSimulationToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentSimulationToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentSimulationToken' from JSON`,
  );
}
