/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ForkSimulationRequest = {
  /**
   * Completed step to fork from. Omission forks from the latest state.
   */
  atStep?: number | undefined;
  /**
   * Optional child Simulation name. Omission generates a name.
   */
  name?: string | undefined;
};

/** @internal */
export type ForkSimulationRequest$Outbound = {
  at_step?: number | undefined;
  name?: string | undefined;
};

/** @internal */
export const ForkSimulationRequest$outboundSchema: z.ZodMiniType<
  ForkSimulationRequest$Outbound,
  ForkSimulationRequest
> = z.pipe(
  z.object({
    atStep: z.optional(z.int()),
    name: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      atStep: "at_step",
    });
  }),
);

export function forkSimulationRequestToJSON(
  forkSimulationRequest: ForkSimulationRequest,
): string {
  return JSON.stringify(
    ForkSimulationRequest$outboundSchema.parse(forkSimulationRequest),
  );
}
