/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Limitation = {
  /**
   * The operations the limitation affects, readably, or Simulator when it names none.
   */
  location: string;
  /**
   * What the Simulator does differently from the real system.
   */
  message: string;
  /**
   * Operation IDs the limitation affects, or empty when it names none.
   */
  operations: Array<string>;
  /**
   * Whether review confirmed that the pinned contract or the scaffold cannot express the correct behavior. False for a limitation the build recorded after review or that review did not confirm.
   */
  reviewed: boolean;
};

/** @internal */
export const Limitation$inboundSchema: z.ZodMiniType<Limitation, unknown> = z
  .object({
    location: types.string(),
    message: types.string(),
    operations: z.array(types.string()),
    reviewed: types.boolean(),
  });

export function limitationFromJSON(
  jsonString: string,
): SafeParseResult<Limitation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Limitation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Limitation' from JSON`,
  );
}
