/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Credential, Credential$inboundSchema } from "./credential.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListCredentialsResponse = {
  /**
   * Credential metadata in this page, newest first.
   */
  credentials: Array<Credential>;
  /**
   * Cursor for the next page, or null.
   */
  nextCursor: string | null;
};

/** @internal */
export const ListCredentialsResponse$inboundSchema: z.ZodMiniType<
  ListCredentialsResponse,
  unknown
> = z.pipe(
  z.object({
    credentials: z.array(Credential$inboundSchema),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listCredentialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCredentialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCredentialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCredentialsResponse' from JSON`,
  );
}
