/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Step, Step$inboundSchema } from "./step.js";

export type ListSimulationStepsResponse = {
  /**
   * Cursor for the next page, or null.
   */
  nextCursor: string | null;
  /**
   * Recorded steps in this page.
   */
  steps: Array<Step>;
};

/** @internal */
export const ListSimulationStepsResponse$inboundSchema: z.ZodMiniType<
  ListSimulationStepsResponse,
  unknown
> = z.pipe(
  z.object({
    next_cursor: types.nullable(types.string()),
    steps: z.array(Step$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listSimulationStepsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSimulationStepsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSimulationStepsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSimulationStepsResponse' from JSON`,
  );
}
