/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { World, World$inboundSchema } from "./world.js";

export type ListWorldsResponse = {
  /**
   * Cursor for the next page, or null when this is the last page.
   */
  nextCursor: string | null;
  /**
   * Worlds in this page.
   */
  worlds: Array<World>;
};

/** @internal */
export const ListWorldsResponse$inboundSchema: z.ZodMiniType<
  ListWorldsResponse,
  unknown
> = z.pipe(
  z.object({
    next_cursor: types.nullable(types.string()),
    worlds: z.array(World$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listWorldsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWorldsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWorldsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWorldsResponse' from JSON`,
  );
}
