/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ClockEvent, ClockEvent$inboundSchema } from "./clock-event.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListAdvanceEventsOutputBody = {
  /**
   * Committed events in execution order.
   */
  events: Array<ClockEvent>;
  /**
   * Cursor for the next page, or null.
   */
  nextCursor: string | null;
};

/** @internal */
export const ListAdvanceEventsOutputBody$inboundSchema: z.ZodMiniType<
  ListAdvanceEventsOutputBody,
  unknown
> = z.pipe(
  z.object({
    events: z.array(ClockEvent$inboundSchema),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listAdvanceEventsOutputBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListAdvanceEventsOutputBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAdvanceEventsOutputBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAdvanceEventsOutputBody' from JSON`,
  );
}
