/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Simulator, Simulator$inboundSchema } from "./simulator.js";

export type ListSimulatorsResponse = {
  /**
   * Cursor for the next page, or null.
   */
  nextCursor: string | null;
  /**
   * Simulators in this page.
   */
  simulators: Array<Simulator>;
};

/** @internal */
export const ListSimulatorsResponse$inboundSchema: z.ZodMiniType<
  ListSimulatorsResponse,
  unknown
> = z.pipe(
  z.object({
    next_cursor: types.nullable(types.string()),
    simulators: z.array(Simulator$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listSimulatorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSimulatorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSimulatorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSimulatorsResponse' from JSON`,
  );
}
