/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Simulation, Simulation$inboundSchema } from "./simulation.js";

export type ListSimulationsResponse = {
  /**
   * Cursor for the next page, or null.
   */
  nextCursor: string | null;
  /**
   * Simulations in this page.
   */
  simulations: Array<Simulation>;
};

/** @internal */
export const ListSimulationsResponse$inboundSchema: z.ZodMiniType<
  ListSimulationsResponse,
  unknown
> = z.pipe(
  z.object({
    next_cursor: types.nullable(types.string()),
    simulations: z.array(Simulation$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listSimulationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSimulationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSimulationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSimulationsResponse' from JSON`,
  );
}
