/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type MintSimulationTokenRequest = {
  /**
   * Token lifetime in seconds, from 60 through 86,400.
   */
  ttlSeconds: number;
};

/** @internal */
export type MintSimulationTokenRequest$Outbound = {
  ttl_seconds: number;
};

/** @internal */
export const MintSimulationTokenRequest$outboundSchema: z.ZodMiniType<
  MintSimulationTokenRequest$Outbound,
  MintSimulationTokenRequest
> = z.pipe(
  z.object({
    ttlSeconds: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      ttlSeconds: "ttl_seconds",
    });
  }),
);

export function mintSimulationTokenRequestToJSON(
  mintSimulationTokenRequest: MintSimulationTokenRequest,
): string {
  return JSON.stringify(
    MintSimulationTokenRequest$outboundSchema.parse(mintSimulationTokenRequest),
  );
}
