/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ResourceError = {
  /**
   * Stable machine-readable error code.
   */
  code: string;
  /**
   * Safe human-readable error detail.
   */
  detail: string;
};

/** @internal */
export const ResourceError$inboundSchema: z.ZodMiniType<
  ResourceError,
  unknown
> = z.object({
  code: types.string(),
  detail: types.string(),
});

export function resourceErrorFromJSON(
  jsonString: string,
): SafeParseResult<ResourceError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceError' from JSON`,
  );
}
