/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ResourceError,
  ResourceError$inboundSchema,
} from "./resource-error.js";

/**
 * Simulator source.
 */
export const Source = {
  Workspace: "workspace",
  Catalog: "catalog",
} as const;
/**
 * Simulator source.
 */
export type Source = OpenEnum<typeof Source>;

/**
 * Current build status.
 */
export const SimulatorStatus = {
  Building: "building",
  Ready: "ready",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * Current build status.
 */
export type SimulatorStatus = OpenEnum<typeof SimulatorStatus>;

export type Simulator = {
  /**
   * Simulator creation time.
   */
  createdAt: Date;
  error: ResourceError | null;
  /**
   * Stable Simulator ID.
   */
  id: string;
  /**
   * Simulator name. Names cannot start with smr_.
   */
  name: string;
  /**
   * Stable parent Simulator ID, or null.
   */
  parentId: string | null;
  /**
   * Simulator source.
   */
  source: Source;
  /**
   * Current build status.
   */
  status: SimulatorStatus;
};

/** @internal */
export const Source$inboundSchema: z.ZodMiniType<Source, unknown> = openEnums
  .inboundSchema(Source);

/** @internal */
export const SimulatorStatus$inboundSchema: z.ZodMiniType<
  SimulatorStatus,
  unknown
> = openEnums.inboundSchema(SimulatorStatus);

/** @internal */
export const Simulator$inboundSchema: z.ZodMiniType<Simulator, unknown> = z
  .pipe(
    z.object({
      created_at: types.date(),
      error: types.nullable(ResourceError$inboundSchema),
      id: types.string(),
      name: types.string(),
      parent_id: types.nullable(types.string()),
      source: Source$inboundSchema,
      status: SimulatorStatus$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "parent_id": "parentId",
      });
    }),
  );

export function simulatorFromJSON(
  jsonString: string,
): SafeParseResult<Simulator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Simulator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Simulator' from JSON`,
  );
}
