/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SimulatorBuildProgress,
  SimulatorBuildProgress$inboundSchema,
} from "./simulator-build-progress.js";
import {
  SimulatorError,
  SimulatorError$inboundSchema,
} from "./simulator-error.js";

/**
 * workspace for a Simulator your workspace built; catalog for a read-only Simulator that Continuous publishes.
 */
export const Source = {
  Workspace: "workspace",
  Catalog: "catalog",
} as const;
/**
 * workspace for a Simulator your workspace built; catalog for a read-only Simulator that Continuous publishes.
 */
export type Source = OpenEnum<typeof Source>;

/**
 * building while the build runs; ready when Simulations, Worlds, and incremental builds can use it; failed when the build failed; canceled when a cancel request took effect.
 */
export const SimulatorStatus = {
  Building: "building",
  Ready: "ready",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * building while the build runs; ready when Simulations, Worlds, and incremental builds can use it; failed when the build failed; canceled when a cancel request took effect.
 */
export type SimulatorStatus = OpenEnum<typeof SimulatorStatus>;

export type Simulator = {
  /**
   * The build's latest progress report, or null before the first report. A terminal Simulator keeps its last report.
   */
  build: SimulatorBuildProgress | null;
  /**
   * Simulator creation time.
   */
  createdAt: Date;
  error: SimulatorError | null;
  /**
   * Simulator ID.
   */
  id: string;
  /**
   * Simulator name. Names cannot start with smr_.
   */
  name: string;
  /**
   * Parent Simulator ID, or null.
   */
  parentId: string | null;
  /**
   * workspace for a Simulator your workspace built; catalog for a read-only Simulator that Continuous publishes.
   */
  source: Source;
  /**
   * building while the build runs; ready when Simulations, Worlds, and incremental builds can use it; failed when the build failed; canceled when a cancel request took effect.
   */
  status: SimulatorStatus;
};

/** @internal */
export const Source$inboundSchema: z.ZodMiniType<Source, unknown> = openEnums
  .inboundSchema(Source);

/** @internal */
export const SimulatorStatus$inboundSchema: z.ZodMiniType<
  SimulatorStatus,
  unknown
> = openEnums.inboundSchema(SimulatorStatus);

/** @internal */
export const Simulator$inboundSchema: z.ZodMiniType<Simulator, unknown> = z
  .pipe(
    z.object({
      build: types.nullable(SimulatorBuildProgress$inboundSchema),
      created_at: types.date(),
      error: types.nullable(SimulatorError$inboundSchema),
      id: types.string(),
      name: types.string(),
      parent_id: types.nullable(types.string()),
      source: Source$inboundSchema,
      status: SimulatorStatus$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "parent_id": "parentId",
      });
    }),
  );

export function simulatorFromJSON(
  jsonString: string,
): SafeParseResult<Simulator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Simulator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Simulator' from JSON`,
  );
}
