/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SimulatorActor = {
  /**
   * Whether a request without the header acts as this caller.
   */
  default: boolean;
  /**
   * The entity whose row the id keys.
   */
  entity: string;
  /**
   * The value to send in the X-Continuous-Actor header: the key of the identity row the caller acts as.
   */
  id: string;
  /**
   * The build's name for the caller.
   */
  name: string;
  /**
   * The caller's role in the simulated service.
   */
  role: string;
};

/** @internal */
export const SimulatorActor$inboundSchema: z.ZodMiniType<
  SimulatorActor,
  unknown
> = z.object({
  default: types.boolean(),
  entity: types.string(),
  id: types.string(),
  name: types.string(),
  role: types.string(),
});

export function simulatorActorFromJSON(
  jsonString: string,
): SafeParseResult<SimulatorActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulatorActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulatorActor' from JSON`,
  );
}
