/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SpecificationWarning,
  SpecificationWarning$inboundSchema,
} from "./specification-warning.js";

/**
 * Outcome of the most recent submit attempt, or null.
 */
export const SimulatorBuildProgressLastSubmission = {
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
/**
 * Outcome of the most recent submit attempt, or null.
 */
export type SimulatorBuildProgressLastSubmission = OpenEnum<
  typeof SimulatorBuildProgressLastSubmission
>;

/**
 * The model the builder and reviewer run on. A build recorded before model selection reports its provider's default.
 */
export const SimulatorBuildProgressModel = {
  Gpt6Astra: "gpt-6-astra",
  Gpt6Sol: "gpt-6-sol",
  ClaudeOpus55: "claude-opus-5-5",
  ClaudeFable51: "claude-fable-5-1",
} as const;
/**
 * The model the builder and reviewer run on. A build recorded before model selection reports its provider's default.
 */
export type SimulatorBuildProgressModel = OpenEnum<
  typeof SimulatorBuildProgressModel
>;

/**
 * Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded.
 */
export const SimulatorBuildProgressPhase = {
  Build: "build",
  Review: "review",
  Finalize: "finalize",
} as const;
/**
 * Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded.
 */
export type SimulatorBuildProgressPhase = OpenEnum<
  typeof SimulatorBuildProgressPhase
>;

/**
 * derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
 */
export const SimulatorBuildProgressStage = {
  Derive: "derive",
  Build: "build",
  Assemble: "assemble",
} as const;
/**
 * derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
 */
export type SimulatorBuildProgressStage = OpenEnum<
  typeof SimulatorBuildProgressStage
>;

export type SimulatorBuildProgress = {
  /**
   * Outcome of the most recent submit attempt, or null.
   */
  lastSubmission: SimulatorBuildProgressLastSubmission | null;
  /**
   * Name of the most recent tool call, or null. Tool arguments and output are private.
   */
  lastTool: string | null;
  /**
   * The model the builder and reviewer run on. A build recorded before model selection reports its provider's default.
   */
  model: SimulatorBuildProgressModel;
  /**
   * Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded.
   */
  phase: SimulatorBuildProgressPhase | null;
  /**
   * derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
   */
  stage: SimulatorBuildProgressStage;
  /**
   * Submit attempts.
   */
  submissions: number;
  /**
   * Tool calls the coding loop executed.
   */
  toolCalls: number;
  /**
   * Specification defects the build tolerated without changing the specification, set when the build prepares its specification, and limitations the accepted build records, set when the build is accepted. Empty when none.
   */
  warnings: Array<SpecificationWarning>;
};

/** @internal */
export const SimulatorBuildProgressLastSubmission$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgressLastSubmission,
  unknown
> = openEnums.inboundSchema(SimulatorBuildProgressLastSubmission);

/** @internal */
export const SimulatorBuildProgressModel$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgressModel,
  unknown
> = openEnums.inboundSchema(SimulatorBuildProgressModel);

/** @internal */
export const SimulatorBuildProgressPhase$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgressPhase,
  unknown
> = openEnums.inboundSchema(SimulatorBuildProgressPhase);

/** @internal */
export const SimulatorBuildProgressStage$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgressStage,
  unknown
> = openEnums.inboundSchema(SimulatorBuildProgressStage);

/** @internal */
export const SimulatorBuildProgress$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgress,
  unknown
> = z.pipe(
  z.object({
    last_submission: types.nullable(
      SimulatorBuildProgressLastSubmission$inboundSchema,
    ),
    last_tool: types.nullable(types.string()),
    model: SimulatorBuildProgressModel$inboundSchema,
    phase: types.nullable(SimulatorBuildProgressPhase$inboundSchema),
    stage: SimulatorBuildProgressStage$inboundSchema,
    submissions: types.number(),
    tool_calls: types.number(),
    warnings: z.array(SpecificationWarning$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "last_submission": "lastSubmission",
      "last_tool": "lastTool",
      "tool_calls": "toolCalls",
    });
  }),
);

export function simulatorBuildProgressFromJSON(
  jsonString: string,
): SafeParseResult<SimulatorBuildProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulatorBuildProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulatorBuildProgress' from JSON`,
  );
}
