/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * The coding-loop provider.
 */
export const SimulatorBuildProgressBuilder = {
  Claude: "claude",
  Openai: "openai",
} as const;
/**
 * The coding-loop provider.
 */
export type SimulatorBuildProgressBuilder = OpenEnum<
  typeof SimulatorBuildProgressBuilder
>;

/**
 * Outcome of the most recent submit attempt, or null.
 */
export const LastSubmission = {
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
/**
 * Outcome of the most recent submit attempt, or null.
 */
export type LastSubmission = OpenEnum<typeof LastSubmission>;

/**
 * derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
 */
export const SimulatorBuildProgressStage = {
  Derive: "derive",
  Build: "build",
  Assemble: "assemble",
} as const;
/**
 * derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
 */
export type SimulatorBuildProgressStage = OpenEnum<
  typeof SimulatorBuildProgressStage
>;

export type SimulatorBuildProgress = {
  /**
   * The coding-loop provider.
   */
  builder: SimulatorBuildProgressBuilder;
  /**
   * Outcome of the most recent submit attempt, or null.
   */
  lastSubmission: LastSubmission | null;
  /**
   * Name of the most recent tool call, or null.
   */
  lastTool: string | null;
  /**
   * derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
   */
  stage: SimulatorBuildProgressStage;
  /**
   * Submit attempts.
   */
  submissions: number;
  /**
   * Tool calls the coding loop executed.
   */
  toolCalls: number;
  /**
   * Time of the last progress report.
   */
  updatedAt: Date;
};

/** @internal */
export const SimulatorBuildProgressBuilder$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgressBuilder,
  unknown
> = openEnums.inboundSchema(SimulatorBuildProgressBuilder);

/** @internal */
export const LastSubmission$inboundSchema: z.ZodMiniType<
  LastSubmission,
  unknown
> = openEnums.inboundSchema(LastSubmission);

/** @internal */
export const SimulatorBuildProgressStage$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgressStage,
  unknown
> = openEnums.inboundSchema(SimulatorBuildProgressStage);

/** @internal */
export const SimulatorBuildProgress$inboundSchema: z.ZodMiniType<
  SimulatorBuildProgress,
  unknown
> = z.pipe(
  z.object({
    builder: SimulatorBuildProgressBuilder$inboundSchema,
    last_submission: types.nullable(LastSubmission$inboundSchema),
    last_tool: types.nullable(types.string()),
    stage: SimulatorBuildProgressStage$inboundSchema,
    submissions: types.number(),
    tool_calls: types.number(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "last_submission": "lastSubmission",
      "last_tool": "lastTool",
      "tool_calls": "toolCalls",
      "updated_at": "updatedAt",
    });
  }),
);

export function simulatorBuildProgressFromJSON(
  jsonString: string,
): SafeParseResult<SimulatorBuildProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulatorBuildProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulatorBuildProgress' from JSON`,
  );
}
