/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SimulationToken = {
  /**
   * Token expiration time.
   */
  expiresAt: Date;
  /**
   * New data-plane token.
   */
  token: string;
};

/** @internal */
export const SimulationToken$inboundSchema: z.ZodMiniType<
  SimulationToken,
  unknown
> = z.pipe(
  z.object({
    expires_at: types.date(),
    token: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "expires_at": "expiresAt",
    });
  }),
);

export function simulationTokenFromJSON(
  jsonString: string,
): SafeParseResult<SimulationToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulationToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulationToken' from JSON`,
  );
}
