/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Current Simulation status.
 */
export const SimulationStatus = {
  Running: "running",
  Paused: "paused",
  Stopped: "stopped",
} as const;
/**
 * Current Simulation status.
 */
export type SimulationStatus = OpenEnum<typeof SimulationStatus>;

export type Simulation = {
  /**
   * Simulation creation time.
   */
  createdAt: Date;
  /**
   * Data-plane endpoint for the Simulation.
   */
  endpoint: string;
  /**
   * Stable Simulation ID.
   */
  id: string;
  /**
   * Simulation name.
   */
  name: string;
  /**
   * Stable source Simulation ID for a fork, or null.
   */
  parentId: string | null;
  /**
   * Stable ID of the Simulator.
   */
  simulatorId: string;
  /**
   * Current Simulation status.
   */
  status: SimulationStatus;
};

/** @internal */
export const SimulationStatus$inboundSchema: z.ZodMiniType<
  SimulationStatus,
  unknown
> = openEnums.inboundSchema(SimulationStatus);

/** @internal */
export const Simulation$inboundSchema: z.ZodMiniType<Simulation, unknown> = z
  .pipe(
    z.object({
      created_at: types.date(),
      endpoint: types.string(),
      id: types.string(),
      name: types.string(),
      parent_id: types.nullable(types.string()),
      simulator_id: types.string(),
      status: SimulationStatus$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "parent_id": "parentId",
        "simulator_id": "simulatorId",
      });
    }),
  );

export function simulationFromJSON(
  jsonString: string,
): SafeParseResult<Simulation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Simulation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Simulation' from JSON`,
  );
}
