/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Stable Simulator build error code.
 */
export const SimulatorErrorCode = {
  BuildFailed: "build_failed",
  BuildCancelled: "build_cancelled",
} as const;
/**
 * Stable Simulator build error code.
 */
export type SimulatorErrorCode = OpenEnum<typeof SimulatorErrorCode>;

export type SimulatorError = {
  /**
   * Stable Simulator build error code.
   */
  code: SimulatorErrorCode;
  /**
   * Safe human-readable error detail.
   */
  detail: string;
};

/** @internal */
export const SimulatorErrorCode$inboundSchema: z.ZodMiniType<
  SimulatorErrorCode,
  unknown
> = openEnums.inboundSchema(SimulatorErrorCode);

/** @internal */
export const SimulatorError$inboundSchema: z.ZodMiniType<
  SimulatorError,
  unknown
> = z.object({
  code: SimulatorErrorCode$inboundSchema,
  detail: types.string(),
});

export function simulatorErrorFromJSON(
  jsonString: string,
): SafeParseResult<SimulatorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulatorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulatorError' from JSON`,
  );
}
