/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
 */
export const SimulationStatus = {
  Running: "running",
  Paused: "paused",
  Stopped: "stopped",
} as const;
/**
 * Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
 */
export type SimulationStatus = OpenEnum<typeof SimulationStatus>;

export type Simulation = {
  /**
   * Current clock advance operation ID, or null.
   */
  activeAdvanceId: string | null;
  /**
   * Simulation creation time.
   */
  createdAt: Date;
  /**
   * Current simulated time.
   */
  currentTime: Date;
  /**
   * Base URL for requests to the Simulation.
   */
  endpoint: string;
  /**
   * Simulation ID.
   */
  id: string;
  /**
   * Whether the Simulation started with the Simulator's sample data. A fork inherits its source's state and reports false.
   */
  includeSampleData: boolean;
  /**
   * Customer JSON metadata, or null.
   */
  metadata: any;
  /**
   * Simulation name. The ID is its identity, and names need not be unique.
   */
  name: string;
  /**
   * Source Simulation ID for a fork, or null.
   */
  parentId: string | null;
  /**
   * OCI manifest digest pinned when the Simulation was created.
   */
  simulatorDigest: string;
  /**
   * ID of the Simulator bound to this Simulation.
   */
  simulatorId: string;
  /**
   * Initial simulated time.
   */
  startTime: Date;
  /**
   * Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
   */
  status: SimulationStatus;
  /**
   * ID of the World that owns this Simulation, or null.
   */
  worldId: string | null;
};

/** @internal */
export const SimulationStatus$inboundSchema: z.ZodMiniType<
  SimulationStatus,
  unknown
> = openEnums.inboundSchema(SimulationStatus);

/** @internal */
export const Simulation$inboundSchema: z.ZodMiniType<Simulation, unknown> = z
  .pipe(
    z.object({
      active_advance_id: types.nullable(types.string()),
      created_at: types.date(),
      current_time: types.date(),
      endpoint: types.string(),
      id: types.string(),
      include_sample_data: types.boolean(),
      metadata: z.any(),
      name: types.string(),
      parent_id: types.nullable(types.string()),
      simulator_digest: types.string(),
      simulator_id: types.string(),
      start_time: types.date(),
      status: SimulationStatus$inboundSchema,
      world_id: types.nullable(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "active_advance_id": "activeAdvanceId",
        "created_at": "createdAt",
        "current_time": "currentTime",
        "include_sample_data": "includeSampleData",
        "parent_id": "parentId",
        "simulator_digest": "simulatorDigest",
        "simulator_id": "simulatorId",
        "start_time": "startTime",
        "world_id": "worldId",
      });
    }),
  );

export function simulationFromJSON(
  jsonString: string,
): SafeParseResult<Simulation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Simulation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Simulation' from JSON`,
  );
}
