/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis.
 */
export const SpecificationIssueKind = {
  Invalid: "invalid",
  Unsupported: "unsupported",
  Incomplete: "incomplete",
  Unknown: "unknown",
} as const;
/**
 * Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis.
 */
export type SpecificationIssueKind = OpenEnum<typeof SpecificationIssueKind>;

export type SpecificationIssue = {
  /**
   * Stable validation rule code.
   */
  code: string;
  /**
   * Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis.
   */
  kind: SpecificationIssueKind;
  /**
   * Readable endpoint or field affected by this issue.
   */
  location: string;
  /**
   * What needs attention at this location.
   */
  message: string;
  /**
   * Affected operation ID or method and path, when available. Empty for document-level issues.
   */
  operation: string;
  /**
   * How to correct or address the problem.
   */
  suggestion: string;
};

/** @internal */
export const SpecificationIssueKind$inboundSchema: z.ZodMiniType<
  SpecificationIssueKind,
  unknown
> = openEnums.inboundSchema(SpecificationIssueKind);

/** @internal */
export const SpecificationIssue$inboundSchema: z.ZodMiniType<
  SpecificationIssue,
  unknown
> = z.object({
  code: types.string(),
  kind: SpecificationIssueKind$inboundSchema,
  location: types.string(),
  message: types.string(),
  operation: types.string(),
  suggestion: types.string(),
});

export function specificationIssueFromJSON(
  jsonString: string,
): SafeParseResult<SpecificationIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpecificationIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpecificationIssue' from JSON`,
  );
}
