/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Stable warning code.
 */
export const SpecificationWarningCode = {
  SpecEnumDuplicate: "spec.enum_duplicate",
  SpecPathParameterOptional: "spec.path_parameter_optional",
  SpecDefaultInvalid: "spec.default_invalid",
  SpecResponseUntyped: "spec.response_untyped",
  SpecSchemaLimit: "spec.schema_limit",
  SpecOperationUnservable: "spec.operation_unservable",
  SpecVersionAmbiguous: "spec.version_ambiguous",
  SpecExampleNull: "spec.example_null",
} as const;
/**
 * Stable warning code.
 */
export type SpecificationWarningCode = OpenEnum<
  typeof SpecificationWarningCode
>;

export type SpecificationWarning = {
  /**
   * Stable warning code.
   */
  code: SpecificationWarningCode;
  /**
   * Readable endpoint or field affected by this warning.
   */
  location: string;
  /**
   * What the specification declares and how the build handles it.
   */
  message: string;
  /**
   * Always empty.
   */
  operations: Array<string>;
};

/** @internal */
export const SpecificationWarningCode$inboundSchema: z.ZodMiniType<
  SpecificationWarningCode,
  unknown
> = openEnums.inboundSchema(SpecificationWarningCode);

/** @internal */
export const SpecificationWarning$inboundSchema: z.ZodMiniType<
  SpecificationWarning,
  unknown
> = z.object({
  code: SpecificationWarningCode$inboundSchema,
  location: types.string(),
  message: types.string(),
  operations: z.array(types.string()),
});

export function specificationWarningFromJSON(
  jsonString: string,
): SafeParseResult<SpecificationWarning, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpecificationWarning$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpecificationWarning' from JSON`,
  );
}
