/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SpecificationIssue,
  SpecificationIssue$inboundSchema,
} from "./specification-issue.js";

export type SpecificationValidation = {
  /**
   * Specification validation problems. At most 20 are returned.
   */
  issues: Array<SpecificationIssue>;
};

/** @internal */
export const SpecificationValidation$inboundSchema: z.ZodMiniType<
  SpecificationValidation,
  unknown
> = z.object({
  issues: z.array(SpecificationIssue$inboundSchema),
});

export function specificationValidationFromJSON(
  jsonString: string,
): SafeParseResult<SpecificationValidation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpecificationValidation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpecificationValidation' from JSON`,
  );
}
