/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type StartWorldRequest = {
  /**
   * Initial simulated time for the first Start, in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Saved business dates remain unchanged. Later starts preserve the clock.
   */
  startTime?: Date | undefined;
};

/** @internal */
export type StartWorldRequest$Outbound = {
  start_time?: string | undefined;
};

/** @internal */
export const StartWorldRequest$outboundSchema: z.ZodMiniType<
  StartWorldRequest$Outbound,
  StartWorldRequest
> = z.pipe(
  z.object({
    startTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      startTime: "start_time",
    });
  }),
);

export function startWorldRequestToJSON(
  startWorldRequest: StartWorldRequest,
): string {
  return JSON.stringify(
    StartWorldRequest$outboundSchema.parse(startWorldRequest),
  );
}
