/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Step = {
  /**
   * HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets.
   */
  label: string;
  /**
   * Step number. Use it as at_step when you fork.
   */
  step: number;
};

/** @internal */
export const Step$inboundSchema: z.ZodMiniType<Step, unknown> = z.object({
  label: types.string(),
  step: types.number(),
});

export function stepFromJSON(
  jsonString: string,
): SafeParseResult<Step, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Step$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Step' from JSON`,
  );
}
