/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Step = {
  /**
   * Request label. It usually contains the HTTP method and path.
   */
  label: string;
  /**
   * Completed request number. Use this value as at_step when you fork the Simulation.
   */
  step: number;
};

/** @internal */
export const Step$inboundSchema: z.ZodMiniType<Step, unknown> = z.object({
  label: types.string(),
  step: types.number(),
});

export function stepFromJSON(
  jsonString: string,
): SafeParseResult<Step, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Step$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Step' from JSON`,
  );
}
