/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UpdateCredentialRequest = {
  /**
   * New https URL of the real system.
   */
  baseUrl?: string | undefined;
  /**
   * New HTTP header that carries the value.
   */
  header?: string | undefined;
  /**
   * New credential name.
   */
  name?: string | undefined;
  /**
   * New full header value. Required when base_url or header changes. Builds that start an agent after the change use it. The API never returns it.
   */
  value?: string | undefined;
};

/** @internal */
export type UpdateCredentialRequest$Outbound = {
  base_url?: string | undefined;
  header?: string | undefined;
  name?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const UpdateCredentialRequest$outboundSchema: z.ZodMiniType<
  UpdateCredentialRequest$Outbound,
  UpdateCredentialRequest
> = z.pipe(
  z.object({
    baseUrl: z.optional(z.string()),
    header: z.optional(z.string()),
    name: z.optional(z.string()),
    value: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      baseUrl: "base_url",
    });
  }),
);

export function updateCredentialRequestToJSON(
  updateCredentialRequest: UpdateCredentialRequest,
): string {
  return JSON.stringify(
    UpdateCredentialRequest$outboundSchema.parse(updateCredentialRequest),
  );
}
