/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  BuildToolCall,
  BuildToolCall$inboundSchema,
} from "./build-tool-call.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorldDataSummary,
  WorldDataSummary$inboundSchema,
} from "./world-data-summary.js";

/**
 * Selected model provider, or null for a build created before provider selection.
 */
export const WorldBuildProgressBuilder = {
  Openai: "openai",
  Claude: "claude",
} as const;
/**
 * Selected model provider, or null for a build created before provider selection.
 */
export type WorldBuildProgressBuilder = OpenEnum<
  typeof WorldBuildProgressBuilder
>;

/**
 * Outcome of the most recent plan submission, or null.
 */
export const WorldBuildProgressLastSubmission = {
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
/**
 * Outcome of the most recent plan submission, or null.
 */
export type WorldBuildProgressLastSubmission = OpenEnum<
  typeof WorldBuildProgressLastSubmission
>;

/**
 * Current phase of starting-data preparation.
 */
export const WorldBuildProgressStage = {
  Planning: "planning",
  Generating: "generating",
  Validating: "validating",
  Complete: "complete",
} as const;
/**
 * Current phase of starting-data preparation.
 */
export type WorldBuildProgressStage = OpenEnum<typeof WorldBuildProgressStage>;

export type WorldBuildProgress = {
  /**
   * Selected model provider, or null for a build created before provider selection.
   */
  builder: WorldBuildProgressBuilder | null;
  /**
   * Outcome of the most recent plan submission, or null.
   */
  lastSubmission: WorldBuildProgressLastSubmission | null;
  /**
   * Name of the most recent tool, or null. Tool arguments and output are private.
   */
  lastTool: string | null;
  /**
   * The most recent tool calls, oldest first, at most 20.
   */
  recentTools: Array<BuildToolCall>;
  /**
   * Current phase of starting-data preparation.
   */
  stage: WorldBuildProgressStage;
  /**
   * Number of submitted starting-data plans.
   */
  submissions: number;
  /**
   * Verified starting data, or null before a completed build.
   */
  summary: WorldDataSummary | null;
  /**
   * Number of agent tool calls.
   */
  toolCalls: number;
};

/** @internal */
export const WorldBuildProgressBuilder$inboundSchema: z.ZodMiniType<
  WorldBuildProgressBuilder,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressBuilder);

/** @internal */
export const WorldBuildProgressLastSubmission$inboundSchema: z.ZodMiniType<
  WorldBuildProgressLastSubmission,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressLastSubmission);

/** @internal */
export const WorldBuildProgressStage$inboundSchema: z.ZodMiniType<
  WorldBuildProgressStage,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressStage);

/** @internal */
export const WorldBuildProgress$inboundSchema: z.ZodMiniType<
  WorldBuildProgress,
  unknown
> = z.pipe(
  z.object({
    builder: types.nullable(WorldBuildProgressBuilder$inboundSchema),
    last_submission: types.nullable(
      WorldBuildProgressLastSubmission$inboundSchema,
    ),
    last_tool: types.nullable(types.string()),
    recent_tools: z.array(BuildToolCall$inboundSchema),
    stage: WorldBuildProgressStage$inboundSchema,
    submissions: types.number(),
    summary: types.nullable(WorldDataSummary$inboundSchema),
    tool_calls: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "last_submission": "lastSubmission",
      "last_tool": "lastTool",
      "recent_tools": "recentTools",
      "tool_calls": "toolCalls",
    });
  }),
);

export function worldBuildProgressFromJSON(
  jsonString: string,
): SafeParseResult<WorldBuildProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldBuildProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldBuildProgress' from JSON`,
  );
}
