/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Stable World error code.
 */
export const WorldErrorCode = {
  WorldBuildCanceled: "world_build_canceled",
  WorldStartFailed: "world_start_failed",
  WorldCreateFailed: "world_create_failed",
  WorldFailed: "world_failed",
  WorldPopulationFailed: "world_population_failed",
  WorldPopulationUnsupported: "world_population_unsupported",
  WorldPopulationInvalid: "world_population_invalid",
  WorldPopulationUnavailable: "world_population_unavailable",
} as const;
/**
 * Stable World error code.
 */
export type WorldErrorCode = OpenEnum<typeof WorldErrorCode>;

/**
 * Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field.
 */
export const WorldErrorReason = {
  Canceled: "canceled",
  SpecificationInvalid: "specification_invalid",
  TimeLimit: "time_limit",
  ServiceUnavailable: "service_unavailable",
  BuildFailed: "build_failed",
  PopulationUnsupported: "population_unsupported",
  WorldStartFailed: "world_start_failed",
  WorldOperationFailed: "world_operation_failed",
} as const;
/**
 * Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field.
 */
export type WorldErrorReason = OpenEnum<typeof WorldErrorReason>;

export type WorldError = {
  /**
   * Stable World error code.
   */
  code: WorldErrorCode;
  /**
   * Safe human-readable error detail.
   */
  detail: string;
  /**
   * Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field.
   */
  reason: WorldErrorReason | null;
};

/** @internal */
export const WorldErrorCode$inboundSchema: z.ZodMiniType<
  WorldErrorCode,
  unknown
> = openEnums.inboundSchema(WorldErrorCode);

/** @internal */
export const WorldErrorReason$inboundSchema: z.ZodMiniType<
  WorldErrorReason,
  unknown
> = openEnums.inboundSchema(WorldErrorReason);

/** @internal */
export const WorldError$inboundSchema: z.ZodMiniType<WorldError, unknown> = z
  .object({
    code: WorldErrorCode$inboundSchema,
    detail: types.string(),
    reason: types.nullable(WorldErrorReason$inboundSchema),
  });

export function worldErrorFromJSON(
  jsonString: string,
): SafeParseResult<WorldError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldError' from JSON`,
  );
}
