/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorldBuildProgress,
  WorldBuildProgress$inboundSchema,
} from "./world-build-progress.js";
import { WorldError, WorldError$inboundSchema } from "./world-error.js";
import {
  WorldSimulation,
  WorldSimulation$inboundSchema,
} from "./world-simulation.js";

/**
 * pending while waiting for capacity; building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled.
 */
export const WorldStatus = {
  Pending: "pending",
  Building: "building",
  Ready: "ready",
  Running: "running",
  Stopped: "stopped",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * pending while waiting for capacity; building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled.
 */
export type WorldStatus = OpenEnum<typeof WorldStatus>;

export type World = {
  /**
   * Current clock advance operation ID, or null.
   */
  activeAdvanceId: string | null;
  /**
   * The build's latest progress report and verified starting data, or null before the first report.
   */
  build: WorldBuildProgress | null;
  /**
   * Time when the World was created.
   */
  createdAt: Date;
  /**
   * Current shared simulated time.
   */
  currentTime: Date;
  error: WorldError | null;
  /**
   * World ID.
   */
  id: string;
  /**
   * Instructions for the initial synthetic data and relationships.
   */
  instructions: string;
  /**
   * Customer JSON metadata, or null.
   */
  metadata: any;
  /**
   * Name for the World.
   */
  name: string;
  /**
   * Created member Simulations. This list is empty before first start.
   */
  simulations: Array<WorldSimulation>;
  /**
   * Simulator IDs in member order.
   */
  simulators: Array<string>;
  /**
   * Simulated time the World starts at: chosen at build, and changeable on the first Start.
   */
  startTime: Date;
  /**
   * pending while waiting for capacity; building while the build runs; ready when it can be started; running or stopped once its Simulations exist; failed when building or first start fails; canceled when the build was canceled.
   */
  status: WorldStatus;
};

/** @internal */
export const WorldStatus$inboundSchema: z.ZodMiniType<WorldStatus, unknown> =
  openEnums.inboundSchema(WorldStatus);

/** @internal */
export const World$inboundSchema: z.ZodMiniType<World, unknown> = z.pipe(
  z.object({
    active_advance_id: types.nullable(types.string()),
    build: types.nullable(WorldBuildProgress$inboundSchema),
    created_at: types.date(),
    current_time: types.date(),
    error: types.nullable(WorldError$inboundSchema),
    id: types.string(),
    instructions: types.string(),
    metadata: z.any(),
    name: types.string(),
    simulations: z.array(WorldSimulation$inboundSchema),
    simulators: z.array(types.string()),
    start_time: types.date(),
    status: WorldStatus$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_advance_id": "activeAdvanceId",
      "created_at": "createdAt",
      "current_time": "currentTime",
      "start_time": "startTime",
    });
  }),
);

export function worldFromJSON(
  jsonString: string,
): SafeParseResult<World, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => World$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'World' from JSON`,
  );
}
