/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WorldRecordCount = {
  /**
   * Number of stored starting records of this type.
   */
  count: number;
  /**
   * Record type reported by the Simulator.
   */
  entity: string;
  /**
   * Position in the selected Simulator list, starting at zero.
   */
  memberIndex: number;
  /**
   * Stable ID of the Simulator for this member.
   */
  simulatorId: string;
};

/** @internal */
export const WorldRecordCount$inboundSchema: z.ZodMiniType<
  WorldRecordCount,
  unknown
> = z.pipe(
  z.object({
    count: types.number(),
    entity: types.string(),
    member_index: types.number(),
    simulator_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "member_index": "memberIndex",
      "simulator_id": "simulatorId",
    });
  }),
);

export function worldRecordCountFromJSON(
  jsonString: string,
): SafeParseResult<WorldRecordCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldRecordCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldRecordCount' from JSON`,
  );
}
