/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  BuildToolCall,
  BuildToolCall$inboundSchema,
} from "./build-tool-call.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorldDataSummary,
  WorldDataSummary$inboundSchema,
} from "./world-data-summary.js";

/**
 * Selected model provider, or null for a build created before provider selection.
 */
export const WorldBuildProgressBuilder = {
  Openai: "openai",
  Claude: "claude",
} as const;
/**
 * Selected model provider, or null for a build created before provider selection.
 */
export type WorldBuildProgressBuilder = OpenEnum<
  typeof WorldBuildProgressBuilder
>;

/**
 * Outcome of the most recent plan submission, or null.
 */
export const WorldBuildProgressLastSubmission = {
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
/**
 * Outcome of the most recent plan submission, or null.
 */
export type WorldBuildProgressLastSubmission = OpenEnum<
  typeof WorldBuildProgressLastSubmission
>;

/**
 * Fixed code for the latest validation finding. Null when no finding is available. Authored details stay private.
 */
export const LastValidationCode = {
  InvalidPlan: "invalid_plan",
  UnsupportedClaim: "unsupported_claim",
  InvalidRequirement: "invalid_requirement",
  NestedProof: "nested_proof",
  RequestNotSatisfied: "request_not_satisfied",
  VerificationUnavailable: "verification_unavailable",
} as const;
/**
 * Fixed code for the latest validation finding. Null when no finding is available. Authored details stay private.
 */
export type LastValidationCode = OpenEnum<typeof LastValidationCode>;

/**
 * The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default.
 */
export const WorldBuildProgressModel = {
  Gpt6Astra: "gpt-6-astra",
  Gpt6Sol: "gpt-6-sol",
  ClaudeOpus55: "claude-opus-5-5",
  ClaudeFable51: "claude-fable-5-1",
} as const;
/**
 * The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default.
 */
export type WorldBuildProgressModel = OpenEnum<typeof WorldBuildProgressModel>;

/**
 * Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded.
 */
export const WorldBuildProgressPhase = {
  Build: "build",
  Review: "review",
  Finalize: "finalize",
} as const;
/**
 * Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded.
 */
export type WorldBuildProgressPhase = OpenEnum<typeof WorldBuildProgressPhase>;

/**
 * Status of the original independent review, not approval of later edits. Null before review.
 */
export const ReviewStatus = {
  Pending: "pending",
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
/**
 * Status of the original independent review, not approval of later edits. Null before review.
 */
export type ReviewStatus = OpenEnum<typeof ReviewStatus>;

/**
 * Internal step of starting-data preparation.
 */
export const WorldBuildProgressStage = {
  Planning: "planning",
  Generating: "generating",
  Validating: "validating",
  Reviewing: "reviewing",
  Complete: "complete",
} as const;
/**
 * Internal step of starting-data preparation.
 */
export type WorldBuildProgressStage = OpenEnum<typeof WorldBuildProgressStage>;

export type WorldBuildProgress = {
  /**
   * Selected model provider, or null for a build created before provider selection.
   */
  builder: WorldBuildProgressBuilder | null;
  /**
   * Outcome of the most recent plan submission, or null.
   */
  lastSubmission: WorldBuildProgressLastSubmission | null;
  /**
   * Name of the most recent tool, or null. Tool arguments and output are private.
   */
  lastTool: string | null;
  /**
   * Fixed code for the latest validation finding. Null when no finding is available. Authored details stay private.
   */
  lastValidationCode: LastValidationCode | null;
  /**
   * The model the builder and reviewer run on, or null for a build created before provider selection. A build recorded before model selection reports its provider's default.
   */
  model: WorldBuildProgressModel | null;
  /**
   * Agent phase: build for generation, review for the separate reviewer, finalize for author repair after review. Null when not recorded.
   */
  phase: WorldBuildProgressPhase | null;
  /**
   * The most recent tool calls, oldest first, at most 20.
   */
  recentTools: Array<BuildToolCall>;
  /**
   * Status of the original independent review, not approval of later edits. Null before review.
   */
  reviewStatus: ReviewStatus | null;
  /**
   * Internal step of starting-data preparation.
   */
  stage: WorldBuildProgressStage;
  /**
   * Number of distinct candidate plans submitted.
   */
  submissions: number;
  /**
   * Verified starting data, or null before a completed build.
   */
  summary: WorldDataSummary | null;
  /**
   * Number of distinct candidate plans tested. Zero when not recorded.
   */
  tests: number;
  /**
   * Number of agent tool calls.
   */
  toolCalls: number;
};

/** @internal */
export const WorldBuildProgressBuilder$inboundSchema: z.ZodMiniType<
  WorldBuildProgressBuilder,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressBuilder);

/** @internal */
export const WorldBuildProgressLastSubmission$inboundSchema: z.ZodMiniType<
  WorldBuildProgressLastSubmission,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressLastSubmission);

/** @internal */
export const LastValidationCode$inboundSchema: z.ZodMiniType<
  LastValidationCode,
  unknown
> = openEnums.inboundSchema(LastValidationCode);

/** @internal */
export const WorldBuildProgressModel$inboundSchema: z.ZodMiniType<
  WorldBuildProgressModel,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressModel);

/** @internal */
export const WorldBuildProgressPhase$inboundSchema: z.ZodMiniType<
  WorldBuildProgressPhase,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressPhase);

/** @internal */
export const ReviewStatus$inboundSchema: z.ZodMiniType<ReviewStatus, unknown> =
  openEnums.inboundSchema(ReviewStatus);

/** @internal */
export const WorldBuildProgressStage$inboundSchema: z.ZodMiniType<
  WorldBuildProgressStage,
  unknown
> = openEnums.inboundSchema(WorldBuildProgressStage);

/** @internal */
export const WorldBuildProgress$inboundSchema: z.ZodMiniType<
  WorldBuildProgress,
  unknown
> = z.pipe(
  z.object({
    builder: types.nullable(WorldBuildProgressBuilder$inboundSchema),
    last_submission: types.nullable(
      WorldBuildProgressLastSubmission$inboundSchema,
    ),
    last_tool: types.nullable(types.string()),
    last_validation_code: types.nullable(LastValidationCode$inboundSchema),
    model: types.nullable(WorldBuildProgressModel$inboundSchema),
    phase: types.nullable(WorldBuildProgressPhase$inboundSchema),
    recent_tools: z.array(BuildToolCall$inboundSchema),
    review_status: types.nullable(ReviewStatus$inboundSchema),
    stage: WorldBuildProgressStage$inboundSchema,
    submissions: types.number(),
    summary: types.nullable(WorldDataSummary$inboundSchema),
    tests: types.number(),
    tool_calls: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "last_submission": "lastSubmission",
      "last_tool": "lastTool",
      "last_validation_code": "lastValidationCode",
      "recent_tools": "recentTools",
      "review_status": "reviewStatus",
      "tool_calls": "toolCalls",
    });
  }),
);

export function worldBuildProgressFromJSON(
  jsonString: string,
): SafeParseResult<WorldBuildProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldBuildProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldBuildProgress' from JSON`,
  );
}
