/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorldRecordCount,
  WorldRecordCount$inboundSchema,
} from "./world-record-count.js";

export type WorldDataSummary = {
  /**
   * Defaults and inferred choices used to prepare the starting data.
   */
  assumptions: Array<string>;
  /**
   * Record conditions and counts computed from a complete census of served records.
   */
  conditions: Array<string>;
  /**
   * Observed starting record counts for each member and record type.
   */
  records: Array<WorldRecordCount>;
  /**
   * Shared relationships checked against the data and served API values.
   */
  relationships: Array<string>;
};

/** @internal */
export const WorldDataSummary$inboundSchema: z.ZodMiniType<
  WorldDataSummary,
  unknown
> = z.object({
  assumptions: z.array(types.string()),
  conditions: z.array(types.string()),
  records: z.array(WorldRecordCount$inboundSchema),
  relationships: z.array(types.string()),
});

export function worldDataSummaryFromJSON(
  jsonString: string,
): SafeParseResult<WorldDataSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldDataSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldDataSummary' from JSON`,
  );
}
