/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WorldSimulation = {
  /**
   * Stable ID of the created Simulation.
   */
  id: string;
  /**
   * Stable ID of the Simulator that this Simulation runs.
   */
  simulatorId: string;
};

/** @internal */
export const WorldSimulation$inboundSchema: z.ZodMiniType<
  WorldSimulation,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    simulator_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "simulator_id": "simulatorId",
    });
  }),
);

export function worldSimulationFromJSON(
  jsonString: string,
): SafeParseResult<WorldSimulation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldSimulation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldSimulation' from JSON`,
  );
}
