/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorldDataSummary,
  WorldDataSummary$inboundSchema,
} from "./world-data-summary.js";

/**
 * Current phase of starting-data preparation.
 */
export const WorldBuildStage = {
  Planning: "planning",
  Generating: "generating",
  Validating: "validating",
  Complete: "complete",
} as const;
/**
 * Current phase of starting-data preparation.
 */
export type WorldBuildStage = OpenEnum<typeof WorldBuildStage>;

export type WorldBuild = {
  /**
   * Current phase of starting-data preparation.
   */
  stage: WorldBuildStage;
  summary?: WorldDataSummary | undefined;
};

/** @internal */
export const WorldBuildStage$inboundSchema: z.ZodMiniType<
  WorldBuildStage,
  unknown
> = openEnums.inboundSchema(WorldBuildStage);

/** @internal */
export const WorldBuild$inboundSchema: z.ZodMiniType<WorldBuild, unknown> = z
  .object({
    stage: WorldBuildStage$inboundSchema,
    summary: types.optional(WorldDataSummary$inboundSchema),
  });

export function worldBuildFromJSON(
  jsonString: string,
): SafeParseResult<WorldBuild, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorldBuild$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorldBuild' from JSON`,
  );
}
