/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ResourceError,
  ResourceError$inboundSchema,
} from "./resource-error.js";
import {
  WorldSimulation,
  WorldSimulation$inboundSchema,
} from "./world-simulation.js";

/**
 * Current World lifecycle status.
 */
export const WorldStatus = {
  Building: "building",
  Ready: "ready",
  Running: "running",
  Stopped: "stopped",
  Failed: "failed",
  Canceled: "canceled",
} as const;
/**
 * Current World lifecycle status.
 */
export type WorldStatus = OpenEnum<typeof WorldStatus>;

export type World = {
  /**
   * Time when the World build started.
   */
  createdAt: Date;
  error: ResourceError | null;
  /**
   * Stable World ID.
   */
  id: string;
  /**
   * Build guidance stored with the World.
   */
  instructions: string;
  /**
   * Created member Simulations. This list is empty before first start.
   */
  simulations: Array<WorldSimulation>;
  /**
   * Stable Simulator IDs in member order.
   */
  simulators: Array<string>;
  /**
   * Current World lifecycle status.
   */
  status: WorldStatus;
};

/** @internal */
export const WorldStatus$inboundSchema: z.ZodMiniType<WorldStatus, unknown> =
  openEnums.inboundSchema(WorldStatus);

/** @internal */
export const World$inboundSchema: z.ZodMiniType<World, unknown> = z.pipe(
  z.object({
    created_at: types.date(),
    error: types.nullable(ResourceError$inboundSchema),
    id: types.string(),
    instructions: types.string(),
    simulations: z.array(WorldSimulation$inboundSchema),
    simulators: z.array(types.string()),
    status: WorldStatus$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function worldFromJSON(
  jsonString: string,
): SafeParseResult<World, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => World$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'World' from JSON`,
  );
}
