name: Generate

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      force:
        description: Force generation even when the source is unchanged
        type: boolean
        default: false
      set_version:
        description: Optionally set a specific SDK version
        type: string

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@68f3bfefb79354d39358bf4699863dabd2cea0f6
    with:
      mode: pr
      target: continuous-typescript
      force: ${{ inputs.force == true && 'true' || 'false' }}
      set_version: ${{ inputs.set_version }}
      skip_testing: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pr_creation_pat: ${{ secrets.SPEAKEASY_GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
